### ISSUE TITLE
Is it possible to stream to multiple servers? Like facebook Live and wowza at the same time. Any help.

### ISSUE THREAD

**Issue by arvindkumar-gr** [LaiFengiOS/LFLiveKit#10]

**Comment by chenliming777** [comment]
目前还没有这个打算,如果修改可以将编码后的数据发送给多台服务器
- (void)audioEncoder:(nullable id<LFAudioEncoding>)encoder audioFrame:(nullable LFAudioFrame*)frame{
    if(self.uploading) [self.socket sendFrame:frame];//<上传
}

- (void)videoEncoder:(nullable id<LFVideoEncoding>)encoder videoFrame:(nullable LFVideoFrame*)frame{
    if(self.uploading) [self.socket sendFrame:frame];//<上传
}

**Comment by toss156** [comment]
We do not push stream to multiple servers with mobile phone . Do it with one of your servers.

**Comment by arvindkumar-gr** [comment]
Somehow I have managed to do using this awesome library. Now am able to stream to FB and wowza at the same time using different socket. But I have to analyse the consequences. :)

**Comment by telip007** [comment]
@arvindkumar-gr did you made any progress, I would be interested too... Or should I handle this server side ?

**Comment by chenliming777** [comment]
Multiple server upload main problem is the error handling more complex, for example, the way out of the problem，this has not yet been good how to deal with

**Comment by krank21** [comment]
any luck with this? Trying from my end as well... duplicating streams?
