### ISSUE TITLE
关于画面清晰度的疑问

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#101]
你好,我分析了花椒的视频参数:Res:504x896, 15fps.
我在相同的参数下推流,发现怎么调码率都无法达到跟它相同的清晰度.
请问这个还跟什么设置有关?

**Comment by toss156** [comment]
还有可能和 编码方式，编码级别，以及摄像头的分辨率有关（iPhone 6s之前的前置摄像头分辨率太低了）

**Comment by toss156** [comment]
不过同样的设备，我对比过 LFLiveKit和VideoCore，确实还是VideoCore清楚一点，这也是我一直疑惑的地方

**Comment by hellerchen** [comment]
@toss156 确实,我对比了其他几家直播平台(例如栗子直播),用的是VideoCore,确实清晰度上面会比较清楚一点,我对比过VT的编码配置,也没看出个所以然来

**Comment by toss156** [comment]
还有另外一个猜测是和GPUImage 有关，VideoCore输入用的BRGA，GPUImages使用的YUV。

**Comment by hellerchen** [comment]
@toss156 如果是如你猜想,按理说把美颜关闭的前提下,画面清晰度是一样的

**Comment by toss156** [comment]
关闭美颜你还是经过gpuimage的，而不是camera数据 直接 encode

**Comment by hellerchen** [comment]
@toss156 在关闭美颜的前提下,对比了下画面,确实在脸部皮肤上LFLiveKit显示的效果会偏红润..

**Comment by chenliming777** [comment]
这个确实是 @toss156 分析的  GPUImage拿到的是yuv数据  质量会下降

**Comment by silenCetestifY** [comment]
我也发现这个清晰度的问题，有什么方法可以解决么 @chenliming777 @toss156 @linyehui @hellerchen
