### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by yjg2014** [LaiFengiOS/LFLiveKit#107]
观看端拉的rtmp视频流是黑屏的为什么？只有声音没有图像，分析流显示0帧。

**Comment by yjg2014** [comment]
刚开始是直播过程中播放端卡顿了一下，然后在播放端观看画面静止不动了，导致黑屏

**Comment by chenliming777** [comment]
这个有没有步骤什么的

**Comment by yjg2014** [comment]
是的， 推流端抓取的日志发现是断流导致的。目前的现象是推流端在不固定的情况下，会调用以下两个代理：
- (void)liveSession:(nullable LFLiveSession*)session errorCode:(LFLiveSocketErrorCode)errorCode;
- (void)liveSession:(nullable LFLiveSession *)session liveStateDidChange:(LFLiveState)state方法中LFLiveError;
推流端的rtmpSocket会偶尔断开，这是为什么呢？
在这两个代理方法中需要处理推流设置吗？

**Comment by yjg2014** [comment]
@chenliming777 我建了个LFLiveKit库的QQ研发交流群， 592117743，邀请您加入。

**Comment by chenliming777** [comment]
经过沟通可能是断流导致的问题
