### ISSUE TITLE
录屏

### ISSUE THREAD

**Issue by sunjian283019** [LaiFengiOS/LFLiveKit#109]
在README中发现有录屏的功能，但是在实测中没发现录屏的功能啊

**Comment by chenliming777** [comment]
录屏这个功能暂时没有提交  在等等吧  最近提交

**Comment by uldara1** [comment]
hi bro

LFLive support for swift 3 or not ?


Best Regards !
UL DARA
Tel: 088 99 77 087

**Comment by huoshanshi** [comment]
录屏功能什么时候能提交啊，大神

**Comment by chenliming777** [comment]
是游戏直播那一套不，我一直没提交是因为感觉没什么东西

**Comment by huoshanshi** [comment]
你说的是replay吧，这个貌似只能再游戏中才能用。有没有其他好用的录屏方式

**Comment by huoshanshi** [comment]
你说的是replay吧，这个貌似只能在游戏中才能用。有没有其他好用的录屏方式？

**Comment by toss156** [comment]
@huoshanshi iOS9以下的使用私有api可以实现搜索（RecordMyScreen），iOS9以上的一般采用airplay的方式
