### ISSUE TITLE
直播停止不了!!!

### ISSUE THREAD

**Issue by GitHubWanglei** [LaiFengiOS/LFLiveKit#11]
停止直播调用`[_self.session stopLive]`后, 直播状态由`已连接`变为`连接中`, 又变为`已连接`, 停止不掉!
![2016-07-14 17 33 23](https://cloud.githubusercontent.com/assets/16434720/16835073/71307802-49e9-11e6-8e7f-8bb40e5fa7ca.png)

**Comment by chenliming777** [comment]
谢谢反馈 这个已经解掉了(目前可以看提交日至，在你的本地仓库改一下)，但目前cocoapod没有更新新的版本 ，最晚明天晚上更新（因为还有别的bug需要解，谢谢理解）

**Comment by zzgo** [comment]
这个问题我目前使用仍然存在。。调用stopLive关闭直播后，我在服务器上，仍然可以听到或者看到流的信息，没有断开推流

**Comment by chenliming777** [comment]
是develop版本吗

**Comment by hellerchen** [comment]
你好,在某些场景下这个bug貌似还存在,例如频繁切换网络(例如WIFI->3G/4G),多次开启和关闭网络

**Comment by zzgo** [comment]
@chenliming777 我用pod集成的，可能是我的版本不对？

**Comment by chenliming777** [comment]
用最新的1.9.0测测吧

**Comment by hellerchen** [comment]
刚用1.9.0测试过,在WIFI切换到3G网络,会不断重连,这时候点击停止直播,会复现这个问题

**Comment by hellerchen** [comment]
关于这个bug,在LFLiveSession中的stopLive作以下处理好像就可以:
- (void)stopLive {
    self.uploading = NO;
    [self.socket stop];
    self.socket = nil;
}

**Comment by chenliming777** [comment]
好的  我这边按你的思路提交一下，然后后期再测试一下吧 ，非常感谢

**Comment by zzgo** [comment]
作者辛苦了。
另外直播时，不能自动旋转的具体原因是什么呢？我之前用videocore的时候，也是用gpuimage来做，好像控制屏幕旋转也没有问题啊。

**Comment by chenliming777** [comment]
已经提交了。目前仅支持横屏自动转，与竖屏自动转，还没有做到横竖屏自动转（这里需要服务器支持）
