### ISSUE TITLE
支持将视频保存到本地吗

### ISSUE THREAD

**Issue by lovexiaohuangdou** [LaiFengiOS/LFLiveKit#110]
rt！

**Comment by chenliming777** [comment]
这个已经支持了  
![89086b3b-d9f8-4262-8ae0-93d7354274a5](https://cloud.githubusercontent.com/assets/8952943/19302474/dde6728c-9096-11e6-9acf-36998627e22c.png)

**Comment by zj381652512** [comment]
> 这个已经支持了
> ![89086b3b-d9f8-4262-8ae0-93d7354274a5](https://cloud.githubusercontent.com/assets/8952943/19302474/dde6728c-9096-11e6-9acf-36998627e22c.png)
1.在self.saveLocalVideo=YES前提下,保存视频到本地,是GPUImage处理后的数据? 还是在压缩之后rtmp封装之前的数据?
2.目前录制视频10s大概有5M,录制一个小时约1.5G以上,session是否有控制视频的压缩的接口?
3.如果只有音频推流, 如何处理比较好? session是否有接口?
