### ISSUE TITLE
Can't archive due to bitcode error

### ISSUE THREAD

**Issue by dmdque** [LaiFengiOS/LFLiveKit#113]
When trying to Archive my project which uses LFLiveKit, I get the following error:

```
ld: bitcode bundle could not be generated because '/path-to-project/Pods/LFLiveKit/Vendor/pili-librtmp.framework/pili-librtmp(amf.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It doesn't work whether I set `Enable Bitcode` to `YES` or `NO`.

**Comment by yjg2014** [comment]
you can try to set Enable Bitcode to NO

**Comment by takezou621** [comment]
> It doesn't work whether I set Enable Bitcode to YES or NO.
Me too.can't archive my project even if bitcode NO.

**Comment by TheRyanHickman** [comment]
same issue. =( regardless of what i set bitcode to

**Comment by znja** [comment]
Having the same issue. Anyone found a workaround for this?

**Comment by TheRyanHickman** [comment]
![image](https://cloud.githubusercontent.com/assets/2328000/20011758/0f65b4aa-a283-11e6-8445-758a00d60a28.png)

what i did was disabled bitcode at the project level, and then also on the specific pod, just as a workaround for now.

**Comment by TheRyanHickman** [comment]
problem now is i get a Mach-O-Linker error when trying to upload.

**Comment by toss156** [comment]
You can rebuild the [pili-librtmp.framework](https://github.com/pili-engineering/pili-librtmp) with Bitcode, and they replace the framework in LFLiveKit.

**Comment by BugKiller-tech** [comment]
@toss156 Can you tell me the detailed method?
I've downloaded pili-librtmp.framework repository and built but I got the .a file not .framework file
