### ISSUE TITLE
初始化AudioConvert的时候偶现崩溃

### ISSUE THREAD

**Issue by XFoxer** [LaiFengiOS/LFLiveKit#115]
OSStatus result = AudioConverterNewSpecific(&inputFormat, &outputFormat, 2, requestedCodecs, &m_converter);;
    UInt32 outputBitrate = _configuration.audioBitrate;
    UInt32 propSize = sizeof(outputBitrate);
//    UInt32 outputPacketSize = 0;

    
    if(result == noErr) {
     ///////这里会崩溃
       result = AudioConverterSetProperty(m_converter, kAudioConverterEncodeBitRate, propSize, &outputBitrate);
    }

**Comment by chenliming777** [comment]
不是崩溃 只是断点

**Comment by XFoxer** [comment]
开全局断点确实会断在那里。 这个问题是每次删掉手机App，再重新安装，第一次开播时偶现的，会崩溃在result这个地方。测试粒度是大概10~20次左右会出现一次，也有可能20多次甚至更多次数才会出现一次。
