### ISSUE TITLE
【建议】是否可以将录制接口单独封装出来呢

### ISSUE THREAD

**Issue by jiangzhibin** [LaiFengiOS/LFLiveKit#118]
这里先说下现有逻辑：看了下代码，LFLiveKit的录制 是通过LFLiveSession实例的saveLocalVideo和saveLocalVideoPath来进行录制设置。一个流对应一个本地mp4录制文件。中途来回切换“停止/开始”推流，录制的视频片段 会合并到mp4文件中。

个人感觉不便之处：一个流对应一个LFLiveSession，而录制的设置，是在推流前 边配置好了，实际操作中，一个流长时间推的比重还是挺大的，如果需要录制的，只是这次直播中的某些片段。那现有逻辑就无法满足了（流会持续推，中途不会停止的，录制的视频就从头录到尾了，太过臃肿了）。

【建议】现在的LFLiveKit层没有提供 类似startRecordingToLocalPath:(NSString *)localFilePath / stopRecording 之类的方法，没有便捷的方法，自定义录制需求，从接口设计上，这种方式和现有功能逻辑上，并没有冲突，但可以处理更多的场景。如果可能的话，希望能够实现相关接口。

**Comment by jiangzhibin** [comment]
已经实现

**Comment by zj381652512** [comment]
> 已经实现 

请教一下:
1.在self.saveLocalVideo=YES前提下,保存视频到本地,是GPUImage处理后的数据? 还是在压缩之后rtmp封装之前的数据?
2.目前录制视频10s大概有5M,录制一个小时约1.5G以上,session是否有控制视频的压缩的接口?
3.如果只有音频推流, 如何处理比较好? session是否有接口?
