### ISSUE TITLE
1.8.0 demo 关闭直播,还是会自动链接服务器,状态为已连接

### ISSUE THREAD

**Issue by twenty-zp** [LaiFengiOS/LFLiveKit#12]
同时,如果服务器未打开,点击开始直播后,再次点击播报会崩溃到LFStreamRtmpSockert.m 

```
- (void)_stop{
    if(self.delegate && [self.delegate respondsToSelector:@selector(socketStatus:status:)]){
        [self.delegate socketStatus:self status:LFLiveStop];
    }
    if(_rtmp != NULL){
        PILI_RTMP_Close(_rtmp, &_error);
        PILI_RTMP_Free(_rtmp);
        _rtmp = NULL;
    }
} 
```

**Comment by chenliming777** [comment]
哦哦 这个解了    但没有更新pod

**Comment by chenliming777** [comment]
#哦哦 这个解了    但没有更新pod  把start 里面clean 转移到stop后面好了

**Comment by chenliming777** [comment]
另外你说1.8.0关闭直播  还是会自动链接服务器，这个我这边没复现，LFLiveKitDemo

**Comment by twenty-zp** [comment]
执行的时候,并未到clean 就已经崩溃。 重现: 点击开始直播, 在状态为“连接中“的时候状态为“连接错误”就会崩溃。

**Comment by chenliming777** [comment]
好的  谢谢反馈 我调试好了回复你

**Comment by twenty-zp** [comment]
我这边添加了个 是否和服务器已经连接的判断

```
- (void)_stop{
    if(self.delegate && [self.delegate respondsToSelector:@selector(socketStatus:status:)]){
        [self.delegate socketStatus:self status:LFLiveStop];
    }
    **if(_rtmp != NULL && PILI_RTMP_ConnectStream(_rtmp, 0, &_error) == TRUE)**
    {
        PILI_RTMP_Close(_rtmp, &_error);
        PILI_RTMP_Free(_rtmp);
        _rtmp = NULL;
    }
}
```

**Comment by nnianhou-** [comment]
楼主 LFLiveKit可不可以不支持下swift？

**Comment by chenliming777** [comment]
用swift语言重新写一份还是什么意思

**Comment by nnianhou-** [comment]
@chenliming777  不是重新写一份，swift可以调用OC 。swift创建的工程 通过pod或手动 导入LFLiveKit 编译报错 ,你可以用swift工程试试  最近在写swift项目直播，看到楼主的框架不错，就想试试

**Comment by chenliming777** [comment]
好的 会尝试的

**Comment by chenliming777** [comment]
@twenty-zp   开始直播连接中在点击直播崩溃这个应该好了

**Comment by twenty-zp** [comment]
commit中没看到你修改的代码地方啊

**Comment by chenliming777** [comment]
static dispatch_queue_t YYRtmpSendQueue() {
    static YYDispatchQueuePool *pool;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
         pool  = [[YYDispatchQueuePool alloc] initWithName:@"com.youku.laifeng.rtmpsendQueue" queueCount:1 qos:NSQualityOfServiceDefault];
    });
   
    dispatch_queue_t queue = [pool queue];
    return queue;
}


这里原来线程不是一个的问题导致的

**Comment by chenliming777** [comment]
@nnianhou-   swiftDemo toss156已经写好了，在develop下面
