### ISSUE TITLE
IOS10 美肌問題

### ISSUE THREAD

**Issue by bufei** [LaiFengiOS/LFLiveKit#125]
Assertion failure in -[LFGPUImageBeautyFilter initWithVertexShaderFromString:fragmentShaderFromString, 
GPUImage-master/framework/Source/GPUImageFilter.m:94
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Filter shader link failed'

只有iOS10有問題。其他版本沒事。

**Comment by toss156** [comment]
是什么设备，我这边测试iOS10可以的。感觉可能是和设备有关。

**Comment by bufei** [comment]
iphone 5, iphone 5s,　和 iphone6plus 都有問題
