### ISSUE TITLE
ERROR: PILI_RTMP_ReadPacket, failed to read PILI_RTMP packet header

### ISSUE THREAD

**Issue by remihillairet** [LaiFengiOS/LFLiveKit#127]
Hey,

I started testing LFLiveKit with the code example and I have this error:
`ERROR: PILI_RTMP_ReadPacket, failed to read PILI_RTMP packet header`

What's PILI RTMP ?

I would like to stream to YouTube, I use this code to start streaming:

```
let stream = LFLiveStreamInfo()
stream.url = "rtmp://a.rtmp.youtube.com/live2"
stream.streamId = "xxxx-xxxx-xxxx-xxxx"
session.startLive(stream)
```

> Configuration:
> Xcode 8
> Swift 3
> iOS 10

Thanks,

Remi.

**Comment by chenliming777** [comment]
only need let stream = LFLiveStreamInfo()
stream.url = "xxxx"

**Comment by remihillairet** [comment]
To stream on YouTube I need to specify a stream url and a stream name/key.
I supposed that the stream name/key was streamId here. Is it use for that ?

**Comment by chenliming777** [comment]
sample url : rtmp://live.hkstv.hk.lxdns.com:1935/live/stream153

this streamid  is  stream153

**Comment by remihillairet** [comment]
Ok if I directly append the streamid to the url it works. Thanks.

**Comment by biyu6** [comment]
将 url 改为 rtmp://116.196.87.91:1935/live/VC000051

**Comment by biyu6** [comment]
The reason is that the connection failed.You can try to change the URL to the URL of your own server; or try this:（rtmp：//116.196.87.91：1935 / live / VC000099） Note that ”VC000099“ is custom，Don't repeat it with others。Recommend two software for testing:OBS、VLC

**Comment by GirirajMulay** [comment]
I am also facing same issue while connecting with rtmp server 
ERROR: PILI_RTMP_ReadPacket, failed to read PILI_RTMP packet header
Please help me around that
