### ISSUE TITLE
What about a tap to focus/exposure feature?

### ISSUE THREAD

**Issue by sherm4n90** [LaiFengiOS/LFLiveKit#128]
It would be pretty useful.
Thanks in advance

**Comment by chenliming777** [comment]
AVCaptureDevice *device = (AVCaptureDevice *)self.captureDevice;
    AVCaptureFocusMode newMode = continuousAutofocusEnable ?  AVCaptureFocusModeContinuousAutoFocus : AVCaptureFocusModeAutoFocus;
    bool ret = [device isFocusModeSupported:newMode];
    
    if (ret) {
        NSError *err = nil;
        if ([device lockForConfiguration:&err]) {
            device.focusMode = newMode;
            [device unlockForConfiguration];
        } else {
            NSLog(@"Error while locking device for autofocus: %@", err);
            ret = false;
        }
    } else {
        NSLog(@"Focus mode not supported: %@", continuousAutofocusEnable ? @"AVCaptureFocusModeContinuousAutoFocus" : @"AVCaptureFocusModeAutoFocus");
    }

**Comment by chenliming777** [comment]
我没有实现 你可以借鉴一下

**Comment by sherm4n90** [comment]
@chenliming777 Thanks, I have already implemented with exposure too.

**Comment by iosdev-republicofapps** [comment]
@chenliming777 where do I get access to self.captureDevice in your example?  Who is the self pointer?  I don't see how to access the AVCaptureDevice from LFLiveKit.

@sherm4n90 how did you make this work?

Thanks.  :-)
