### ISSUE TITLE
会有类似于对焦的功能么？

### ISSUE THREAD

**Issue by CHparis** [LaiFengiOS/LFLiveKit#134]
想知道对焦如何实现

**Comment by chenliming777** [comment]
对焦我没有实现 可以实现的  类似这样
AVCaptureDevice *device = (AVCaptureDevice *)self.captureDevice;
    AVCaptureFocusMode newMode = continuousAutofocusEnable ?  AVCaptureFocusModeContinuousAutoFocus : AVCaptureFocusModeAutoFocus;
    bool ret = [device isFocusModeSupported:newMode];
    
    if (ret) {
        NSError *err = nil;
        if ([device lockForConfiguration:&err]) {
            device.focusMode = newMode;
            [device unlockForConfiguration];
        } else {
            NSLog(@"Error while locking device for autofocus: %@", err);
            ret = false;
        }
    } else {
        NSLog(@"Focus mode not supported: %@", continuousAutofocusEnable ? @"AVCaptureFocusModeContinuousAutoFocus" : @"AVCaptureFocusModeAutoFocus");
    }

**Comment by CHparis** [comment]
这一段代码，是需要放到哪个位置就可以了呢

**Comment by chenliming777** [comment]
你搜索一下吧  首先你要有对焦的view  通过手指点击view计算出CGPoint  然后通过point设置

**Comment by chenliming777** [comment]
这一段代码并不是所有的实现
