### ISSUE TITLE
assigning a device position just rotates the camera

### ISSUE THREAD

**Issue by pvinis** [LaiFengiOS/LFLiveKit#135]
lets say i make a session. it has the front camera as default. then i do `_session.captureDevicePosition = AVCaptureDevicePositionBack;`. now its the back camera. all good. now i do `_session.captureDevicePosition = AVCaptureDevicePositionBack;` again. now its the front camera. i saw that the `setVideoCaptureDevicePosition:` in `LFVideoCapture.m` is just rotating the camera, without actually checking what i assign.

**Comment by chenliming777** [comment]
this is a bug . fixed.
