### ISSUE TITLE
Can we stream from IP Camera using RSTP ?

### ISSUE THREAD

**Issue by uldara1** [LaiFengiOS/LFLiveKit#136]

**Comment by toss156** [comment]
Yes, you can decode the rtsp stream first, then push with pushVideo/pushAudio

**Comment by uldara1** [comment]
Thank for your reply 😌 . If have sample for this it's really great 👍

**Comment by allentsing** [comment]
Do you have a demo for pushVideo??

**Comment by uldara1** [comment]
hi i have link stream below. but i don't know how to stream using Lflivekit.
 rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

**Comment by animaonline** [comment]
Were you able to get it working?

**Comment by allentsing** [comment]
This is a demo to pushAudio and pushVideo.  https://github.com/allentsing/ATijkplayeriOS

**Comment by allentsing** [comment]
@uldara1  @animaonline  https://github.com/allentsing/ATijkplayeriOS
