### ISSUE TITLE
Support resolution when camera is in landscape mode

### ISSUE THREAD

**Issue by sarbjit-longia** [LaiFengiOS/LFLiveKit#139]
Currently when we stream using camera the resolution is always fixed where width < height e.g. 360x640. 

When the camera is rotated to landscape mode we shall be able to support resolutions like 640x360.

**Comment by pvinis** [comment]
you can set `landscape` to `YES` in the `videoConfiguration` and that turns it around.

**Comment by danlniel** [comment]
you cant its get-only,
try this one     
`let videoConfiguration = LFLiveVideoConfiguration.defaultConfiguration(for: LFLiveVideoQuality.medium3, outputImageOrientation: .landscapeRight)`

**Comment by timothytlewis** [comment]
Has anyone gotten this to work? Whenever we try to force landscape, the image is skewed. I would love to see an example.
