### ISSUE TITLE
Broken pipe解决思路

### ISSUE THREAD

**Issue by mengxiangyue** [LaiFengiOS/LFLiveKit#14]
我参照你们的库，想学习一下RTMP推流相关的东西，推流的时候遇到了下面的错误：
2016-07-18 09:32:47.802 LiveStudy[923:159136] 数据包    
2016-07-18 09:32:47.802 LiveStudy[923:159136] 时间戳52582565     
ERROR: WriteN, PILI_RTMP send error 32, Broken pipe, (144 bytes)      
ERROR: WriteN, PILI_RTMP send error 32, Broken pipe, (39 bytes) 
ERROR: WriteN, PILI_RTMP send error 32, Broken pipe, (42 bytes)

我学习的代码仓库:https://github.com/mengxiangyue/LiveStudy，  
如果有时间帮忙看一下，没时间的话能给一下思路也十分感谢。

我的逻辑是使用摄像头去捕获数据，目前只是处理视频。然后使用硬件编码最后使用RTMP发送，RTMP发送的代码是基本跟你们库相同，另外我所有的操作都是在主线程的。

十分感谢。

**Comment by chenliming777** [comment]
你这边是每次遇到  还是中途偶尔遇到，这个错误代表的是socket断开了连接，目前develop分支下面实现了重连策略

**Comment by mengxiangyue** [comment]
@chenliming777 是我模仿来疯的库自己写的代码，每次发送六七个包就会断开了，我参考一下你们重连机制试试吧。我不清楚为啥会一直断。

**Comment by chenliming777** [comment]
如果每次都是这样，我猜测是你发送几次数据然后 ，服务器给你强制断开链接了，很有可能是数据哪里有问题。不妨试试本地保存一下看看。

**Comment by mengxiangyue** [comment]
应该是我本地做的错误了，因为我用你们的demo发送数据就没有问题。我再试试吧，我对于视频格式是一点经验没有。十分感谢你的回复。

**Comment by chenliming777** [comment]
嗯 先调试一下吧
