### ISSUE TITLE
画面拉伸

### ISSUE THREAD

**Issue by ltebean** [LaiFengiOS/LFLiveKit#140]
在session running的情况下，如果在当前的view controller开一个ImagePicker并且转到前置摄像头，回来以后画面会出现纵向的拉伸
```
let imagePicker = UIImagePickerController()
imagePicker.sourceType = .camera
imagePicker.delegate = self
imagePicker.allowsEditing = allowsEditing
self.present(imagePicker, animated: true, completion: nil)
```
这样做是想让用户选一张封面图

**Comment by chenliming777** [comment]
我这边监听了相机的变化  监听imagePicker相机关闭后调用如下代码 videoCapture修改的
- (void)closeCamera:(NSNotification *)notification{
    self.running = NO;
    self.videoCamera = nil;
    self.running = YES;
}

**Comment by ltebean** [comment]
我这边要怎么做才能解决这个问题呢？

**Comment by chenliming777** [comment]
你自己监听相机的关闭事件呀
