### ISSUE TITLE
is there any pause and resume feature in the latest version?

### ISSUE THREAD

**Issue by danlniel** [LaiFengiOS/LFLiveKit#142]

**Comment by chenliming777** [comment]
没有 目前只支持setRunning YES OR NO

**Comment by mubinrevcord** [comment]
setRunning NO when button pause click and then again setRunning to YES cause application crash and writer status is getting 2. Because what setRunning is doing is finishWriting when we set running to NO. in that case how to start recording again from the state of pause

**Comment by mubinrevcord** [comment]
Hi @danlniel  Have you figure it out how to pause and resume.... I able to make pause and resume for streaming but for recording pause resume till now i haven't got any solution. 


Thanks in advance!
