### ISSUE TITLE
请问一下，LFLiveKit里面有没有像其他推流器一样可以设置关键帧的变量，是哪个变量？

### ISSUE THREAD

**Issue by fangjinfeng** [LaiFengiOS/LFLiveKit#144]
请问一下，LFLiveKit里面有没有像其他推流器一样可以设置关键帧的变量，是哪个变量？能否帮忙指示一下。麻烦了啊!

**Comment by chenliming777** [comment]
LFLiveVideoConfiguration  videoMaxKeyframeInterval
