### ISSUE TITLE
当videoSizeRespectingAspectRatio=YES时，推流尺寸不对。

### ISSUE THREAD

**Issue by xiangshun110** [LaiFengiOS/LFLiveKit#147]
LFLiveVideoConfiguration *videoConfiguration = [LFLiveVideoConfiguration new];
        videoConfiguration.videoSize = CGSizeMake(640, 360);
        videoConfiguration.videoBitRate = 800*1024;
        videoConfiguration.videoMaxBitRate = 1000*1024;
        videoConfiguration.videoSizeRespectingAspectRatio=YES;
        videoConfiguration.videoMinBitRate = 500*1024;
        videoConfiguration.videoFrameRate = 24;
        videoConfiguration.videoMaxKeyframeInterval = 48;
        videoConfiguration.outputImageOrientation = UIInterfaceOrientationPortrait;
这样推流出去，播放端看到的是这样的：
![wechatimg1](https://cloud.githubusercontent.com/assets/2546146/20747343/ba89b2c2-b724-11e6-83e5-7cdee1cf94d5.png)

发现视频流并不是我设置的640*360这个尺寸或者这个比例。

但是设置videoConfiguration.videoSizeRespectingAspectRatio=NO;的话，播放端就是正常的比例，不过这样视频内容就变形了，不好看:
![wechatimg3](https://cloud.githubusercontent.com/assets/2546146/20747629/bb7463d4-b725-11e6-9bd1-114aaa64c694.jpeg)

**Comment by chenliming777** [comment]
videoSizeRespectingAspectRatio 这个参数的意思就是是否自适应，如果自适应的话内部进行了裁剪缩放等操作

**Comment by chenliming777** [comment]
所以说你可以看看是不是你的sessionPreset是不是设置错了
