### ISSUE TITLE
Crash on closing

### ISSUE THREAD

**Issue by akovalov** [LaiFengiOS/LFLiveKit#148]
Hi!
I have Swift 3 project, view controller with LFLiveSession.
Stream started, streaming good. On stop action I do stopLive() and running = false, then pop view controller and got crash.

<img width="857" alt="screen shot 2016-12-01 at 6 12 48 pm" src="https://cloud.githubusercontent.com/assets/9693643/20801495/cf9ee25e-b7f1-11e6-8e35-788c45648ab7.png">

But if async here change to sync then not crashes.
Could you please help if this is my issue and I'm doing something wrong? Thanks.

**Comment by manajay** [comment]
i think u can use the latest version on branch master to solve this .

Alex Kovalov <notifications@github.com>于2016年12月2日 周五上午12:15写道：

**Comment by akovalov** [comment]
Oh, yes. I had to see that commit. Thank you.
