### ISSUE TITLE
record and stream with different resolutions

### ISSUE THREAD

**Issue by pvinis** [LaiFengiOS/LFLiveKit#151]
is there a way to record in 1080 or 4k and stream at the same time in 720? so it saves locally and then downscales or something before it streams?

**Comment by chrisscholly** [comment]
Any solution to that stuff pls?

**Comment by pvinis** [comment]
no news from me.

**Comment by sunil-targe** [comment]
4K stream really doesn't work at all. Does this support 4K or not?
