### ISSUE TITLE
Change .Portrait to .Landscape dynamic

### ISSUE THREAD

**Issue by ktxc15** [LaiFengiOS/LFLiveKit#155]
Can I change .Portrait to .Landscape in 
    lazy var session: LFLiveSession = {
        let audioConfiguration = LFLiveAudioConfiguration.defaultConfiguration()
        let videoConfiguration = LFLiveVideoConfiguration.defaultConfigurationForQuality(LFLiveVideoQuality.Low3,,outputImageOrientation:.**Portrait**)
        let session = LFLiveSession(audioConfiguration: audioConfiguration, videoConfiguration: videoConfiguration)
        
        session?.delegate = self
        session?.preView = self.view
        return session!
    }()
When rotate iphone 90 degree

**Comment by chenliming777** [comment]
这个需要修改GPUImageVideoCamera outputImageOrientation ,工程暂不支持，因为需要重新上传metadata，重启编码器，另外观看端看视频一会横着一会竖着，感觉很奇怪
