### ISSUE TITLE
Get Gopro video input

### ISSUE THREAD

**Issue by y4nnick** [LaiFengiOS/LFLiveKit#168]
Thanks for the awesome library!

Is it possible (with this library) to get the video input from a gopro?

Here is a link to a tutorial for a other app where you have this feature: http://beebom.com/how-live-stream-facebook-from-gopro-camera/

Unfortunately the app is not open source and i can't find any  information on which library the use. 

Best regards
Yannick

**Comment by SteveLobdell** [comment]
You wouldn't use this library to get video from your gopro.  gopro has a developer sdk I believe, which you would use to receive the video from your gopro, then stuff the frames into this library for publishing.

**Comment by y4nnick** [comment]
Thanks for your answer, are you sure that it is possible (with the gopro sdk) to put the input into this library? 
Have you any experience with this (or sample code)?

**Comment by SteveLobdell** [comment]
Haven't done it, know it's possible.  these are really two unrelated pieces that you'll have to stitch together. Start over at the gopro dev site and figure out out to get the video feed from the gopro to your app. Once you're there, you can worry about streaming it somewhere.

**Comment by y4nnick** [comment]
Thanks, 99$is a little bit expensive just for trying it out for a private project.
Would love to know that it works before investing the money.

I can't find a point in this library where i could get that working.
