### ISSUE TITLE
App crash take image 

### ISSUE THREAD

**Issue by chirag225** [LaiFengiOS/LFLiveKit#169]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Tried to overrelease a framebuffer, did you forget to call -useNextFrameForImageCapture before using -imageFromCurrentFramebuffer?'

**Comment by miinion** [comment]
I think I got this error before.
Can you try running that in main thread?

    dispatch_async(dispatch_get_main_queue(), ^{
        NSData *snapshotImgData = UIImageJPEGRepresentation([self.rtmpLiveSession currentImage],1);
       .....
    });
}

so after running it on main thread, I dont get any crashes anymore.
