### ISSUE TITLE
推流地址错误时界面假死

### ISSUE THREAD

**Issue by glucklili** [LaiFengiOS/LFLiveKit#171]
想问下 为什么LFStreamRTMPSocket.m文件中reconnect方法中，在重连时使用主线程，
dispatch_async(dispatch_get_main_queue(), ^{
                 [self performSelector:@selector(_reconnect) withObject:nil afterDelay:self.reconnectInterval];
            });
现在如果是在推流的url有问题的话，重连时导致了界面假死，得一直等到超时才恢复？

**Comment by leetb-leetb** [comment]
@gluckMu 请问问题解决了吗，求答案

**Comment by JzwOnly** [comment]
@gluckMu  @changbo-He  碰到了相同的问题 请问这个问题怎么解决
