### ISSUE TITLE
Please provide external peripheral example code and screen recording for RTMP streaming 

### ISSUE THREAD

**Issue by dhruvappstack** [LaiFengiOS/LFLiveKit#173]
I wanted to stream my DJI Phantom camera video to RTMP server. Please provide the example code or some custom video buffer sending library.Please also provide screen recording and sharing .

**Comment by pavan4** [comment]
is screen capture possible with LFLiveKit? 

Currently only the front or back cam can be chosen like so, 
`session.captureDevicePosition = .back`

Something like this is possible? 
`session.captureType = .screen` ? // would this be possible? 

I want to use the camera for ARKit and also integrate LFLiveKit as well. Can I use the video feed for both?

**Comment by dhruvappstack** [comment]
@pavan4   LfLiveKit is not useful it has latency
