### ISSUE TITLE
pod 引入 ReactiveCocoa 的时候，LFLiveKit编译失败

### ISSUE THREAD

**Issue by lyandy** [LaiFengiOS/LFLiveKit#18]
如题，当我项目中pod同时引入 ReactiveCocoa 和 LFLiveKit 的时候，LFLiveKit 就会编译失败

我的pod写法入下：

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

use_frameworks!

target 'test' do

pod 'LFLiveKit'
pod 'ReactiveCocoa'

end

**Comment by toss156** [comment]
看起来像是  use_frameworks！引起的

**Comment by lyandy** [comment]
我参考了 [pod insatll can not find header file #9 ](https://github.com/LaiFengiOS/LFLiveKit/issues/18)  你给出的写法，但是问题依旧。

**Comment by toss156** [comment]
其实是pili-librtmp引起的，后面考虑直接使用静态库应该就不会有这个问题了。

**Comment by lyandy** [comment]
还是不能和ReactiveCocoa 在pod里同时引用啊，求解答，怎么才能解决

**Comment by zhangyu528** [comment]
这个问题如何解决的呢？已经参考 pod insatll can not find header file #9 你给出的写法，但是问题依旧
在LK的Demo上也是使用用use_frameworks! 还是找不到文件

**Comment by chenliming777** [comment]
稍等1天左右的时间，我们测试后会重新打包，最新版本应该好了，到时候测试吧

**Comment by zhangyu528** [comment]
good太给力了！

**Comment by chenliming777** [comment]
非常抱歉，今天才解决这个问题，可以尝试了

**Comment by lyandy** [comment]
pod update 更新到 2.0 可以了。感谢解决~
