### ISSUE TITLE
2.5.0版本的LFLiveKit中的GPUImage库是不是自定义的，和官网上的GPUImage不太一样呢

### ISSUE THREAD

**Issue by cky113999742** [LaiFengiOS/LFLiveKit#180]
2.5.0版本的LFLiveKit中的GPUImage库是不是自定义的，和官网上的GPUImage不太一样呢，有些方法是新增的方法，我们工程中本来就GPUImage，再引入显得有些累赘，大家有什么好的方案没？

**Comment by black1997** [comment]
工程中有2个GPUImage，可以编译通过吗？我怎么编译不了？

**Comment by allenlinli** [comment]
請問這個問題有解決嗎？
我打算將 GPUImage 升級到 3，是不是有類似的方法？
