### ISSUE TITLE
延迟较大的问题

### ISSUE THREAD

**Issue by dungeonsnd** [LaiFengiOS/LFLiveKit#181]
我测试发现正常使用的过程中，源视频画面变化后，播放端要过6秒，甚至8秒以上才会看到。也就是延迟达到6-8秒。什么原因导致的？有什么参数可以调整试试看吗？

我测试的环境，
源端使用 iOS8.4.1，
LFLiveKit 2.6
流媒体服务: Nginx+rmtp-module
播放端: vlc播放器
上述都在同一路由器网络中，其中nginx和vlc在同一PC机上。
我在 XCode8.1的输出中看到上传速度在 100KB左右，看似网络带宽不成问题。

2017-02-27 13:34:58.599 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 113.2 KB/s
2017-02-27 13:34:59.621 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 103.3 KB/s
2017-02-27 13:35:00.678 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 107.8 KB/s
2017-02-27 13:35:01.687 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 86.5 KB/s
2017-02-27 13:35:02.708 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 56.7 KB/s
2017-02-27 13:35:03.206 EasyLiveVideo[1235:145634] Increase bitrate 969200
2017-02-27 13:35:03.730 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 62.7 KB/s
2017-02-27 13:35:04.764 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 36.9 KB/s
2017-02-27 13:35:05.768 EasyLiveVideo[1235:145634] debugInfo uploadSpeed: 60.1 KB/s

我使用的参数如下，

`
- (LFLiveSession*)session{
    if(!_session){
        @try {           
            LFLiveAudioConfiguration *audioConfiguration = [LFLiveAudioConfiguration new];
            audioConfiguration.numberOfChannels = 2;
            audioConfiguration.audioBitrate = LFLiveAudioBitRate_32Kbps;
            audioConfiguration.audioSampleRate = LFLiveAudioSampleRate_16000Hz;
            
            LFLiveVideoConfiguration *videoConfiguration = [LFLiveVideoConfiguration defaultConfigurationForQuality:LFLiveVideoQuality_High1];
            videoConfiguration.videoSize = CGSizeMake(960, 540);
            videoConfiguration.videoBitRate = 800*1024;
            videoConfiguration.videoMaxBitRate = 1200*1024;
            videoConfiguration.videoMinBitRate = 400*1024;
            videoConfiguration.videoFrameRate = 10;
            videoConfiguration.videoMaxFrameRate = 15;
            videoConfiguration.videoMinFrameRate = 5;
            videoConfiguration.videoMaxKeyframeInterval = 20;
            videoConfiguration.outputImageOrientation =[[UIApplication sharedApplication] statusBarOrientation];
            videoConfiguration.sessionPreset = LFCaptureSessionPreset540x960;
            
            _session = [[LFLiveSession alloc] initWithAudioConfiguration:audioConfiguration videoConfiguration:videoConfiguration];
            _session.adaptiveBitrate =YES;
            _session.reconnectInterval =8;
            _session.reconnectCount =6;
            
            _session.saveLocalVideo =YES;
            NSString *cachesDir = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) objectAtIndex:0];
            NSString * pathToMovie =[cachesDir stringByAppendingPathComponent:[NSString stringWithFormat:@"%@.mp4", [ELVView dataAndTimeNow]]];
            unlink([pathToMovie UTF8String]); // If a file already exists, AVAssetWriter won't let you record new frames, so delete the old movie
            _session.saveLocalVideoPath =[NSURL fileURLWithPath:pathToMovie];
                        
            _session.showDebugInfo =YES;
            
            // 设置代理
            _session.delegate = self;
            _session.running = YES;
            _session.preView = self;
            _session.captureDevicePosition = AVCaptureDevicePositionBack;
        } @catch (NSException *exception) {
            
        } @finally {
            
        }
    }
    return _session;
}
`

另，作者这个库非常好。感谢~

**Comment by Zeta-XL** [comment]
首先我不是作者,

**Comment by Zeta-XL** [comment]
这个时空物理延迟很大程度会受服务器的影响, 因为服务器是有缓存数据的.
我虽然不是本库的作者, 但是建议你调查一下你们所用服务器对于缓存和延迟的处理

**Comment by dungeonsnd** [comment]
好的。我研究一下服务端看看。

**Comment by notedit** [comment]
减少vlc的缓存buffer

**Comment by dungeonsnd** [comment]
减少vlc的缓存 Network caching (ms) 还是不行。
nginx-rtmp-module 也找过配置指令，试了几个同样不好使。 https://github.com/arut/nginx-rtmp-module/wiki/Directives， 如 buflen 500ms;

**Comment by dungeonsnd** [comment]
对于rtmp，难道 nginx-rtmp-module 就是好几秒以上的延迟?  我换成 srs测试看看。
我发的产品需要在windows平台，但是srs貌似不支持在windows上部署。
from https://github.com/ossrs/srs

![image](https://cloud.githubusercontent.com/assets/4064581/23353729/eb96551c-fd08-11e6-8ed3-2d5a331d4bf8.png)

**Comment by dungeonsnd** [comment]
源端使用下面的参数可以立马把延迟降到2秒左右，是不是gop影响的？ 好神奇。

`
 LFLiveVideoConfiguration *videoConfiguration = [LFLiveVideoConfiguration defaultConfigurationForQuality:LFLiveVideoQuality_High3];

            videoConfiguration.videoSize = CGSizeMake(1280, 720);

            videoConfiguration.outputImageOrientation =[[UIApplication sharedApplication] statusBarOrientation];
`

**Comment by broccolii** [comment]
这个问题在我本地推流时 也有很大的延迟

**Comment by xiakegan05** [comment]
楼主有更好的方法让延迟更短吗
