### ISSUE TITLE
How to pushVideo?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [LaiFengiOS/LFLiveKit#185]
Hi,

Thanks for LFLiveKit, it is great!  :-)

If I want to do a video overlay, how do I push the video to `LFLiveSession.pushVideo`?  Should I invoke this method 30 times per second on my own timer?  Or is there a delegate or callback that I can use to be notified when you need a frame and I can supply it?

Also, will any `CVPixelBuffer` that I supply here by composited with the existing video source (i.e. blended) or will it replace the frame entirely?

I want to blend in an overlay on top of parts of the captured video, but I'm not sure how to do that here.

I understand how to create a `CVPixelBuffer`, just not when or how I should invoke `pushVideo` with the buffer ...

Thanks!

**Comment by chenliming777** [comment]
LFLiveSession  pushVideo

**Comment by DrDepTraii** [comment]
Have you been able to upload the video? Could you provide me with your sample code? I have tried to upload it, but I'm experiencing audio issues. The video, however, is working fine.
