### ISSUE TITLE
iOS 8.3 不能使用LFLiveKit(崩溃)

### ISSUE THREAD

**Issue by XuBaoLoveEatFish** [LaiFengiOS/LFLiveKit#19]
测试时用到了iOS 8.3 发现在GPU处崩溃

**Comment by chenliming777** [comment]
![c607409e-ea83-46c6-bd6c-a8c650970c30](https://cloud.githubusercontent.com/assets/8952943/16977568/6abc5744-4e89-11e6-84bf-7e522fabba5b.jpg)

**Comment by XuBaoLoveEatFish** [comment]
谢谢
