### ISSUE TITLE
Hardware Encoding

### ISSUE THREAD

**Issue by asher636** [LaiFengiOS/LFLiveKit#192]
Hi, 

Thanks for such a great library. But I am stuck in hardware encoding. I'm using HLS for streaming. And HLS needs video in h264. You stated in your feature list that this library supports **H264+AAC Hardware Encoding**. So it would be of great pleasure if you guide me how to use this feature. 

Thanks.

@chenliming777 @toss156

**Comment by wintermox** [comment]
The default is used the hardware encoding feature as long as your device is supported.
