### ISSUE TITLE
LFLiveKit 和 ijkplayer 同时推流和播放时推流不了怎么解决

### ISSUE THREAD

**Issue by yn288163** [LaiFengiOS/LFLiveKit#197]
想要在一个界面同时有播放和推送的功能，但是只要在界面加入了ijkplayer 功能以后就无法正常推送，推送显示连接成功，但是画面声音均无法正常推送

**Comment by yn288163** [comment]
问题解决了，在session初始化前面初始化ijkplayer就可以了~

**Comment by pure8023** [comment]
请问一下 如果需要先推流 再进行拉流呢？  服务端的设置是先返回推流地址。推流成功后再返回 拉流地址  加入ijkplayer拉流  推送显示连接成功，但是声音无法正常推送 这样的话如何解决。如果先初始化ijkplayer 拉流地址没有返回 这样也没有呢

**Comment by JzwOnly** [comment]
@pure8023 请问这个问题j解决了吗
