### ISSUE TITLE
VIDEO NOT SENT AFTER 3 TIMES STREAM

### ISSUE THREAD

**Issue by meilissalee13** [LaiFengiOS/LFLiveKit#198]
I stream about 3 times, then when stream again the video data not sent, PLEASE HELP URGENT!!!

**Comment by wangranGit** [comment]
Do you have to solve this problem now?

**Comment by meilissalee13** [comment]
yes, I see that the stop encoder function never called, and after I called it, it's fixed..

**Comment by timeview** [comment]
How did you called stop encoder - having same issue . It seems that stream goes idle after 3 times
