### ISSUE TITLE
Streaming on Multi Servers

### ISSUE THREAD

**Issue by kk143g** [LaiFengiOS/LFLiveKit#200]
Thank u so much for writing this library LFLivekit, awesome work. Now i want to stream to multiple servers like on Facebook, Youtube at same time. What should i do? I have read that it does not support, but i want it. Any other library or modifications in it?

**Comment by tww0003** [comment]
@kk143g This might not be the solution you're looking for, but if you set up your own RTMP server (I use nginx for mine, it was really easy), you can stream to that server then use the link of that stream to rebroadcast to YouTube/Facebook/Twitch/whatever.

**Comment by kk143g** [comment]
@tww0003 thanks for your suggestion, but i have done with this library quite easily by making more than one SOCKET.
