### ISSUE TITLE
swift下直接设置镜像模式mirror无效

### ISSUE THREAD

**Issue by ilaoxia** [LaiFengiOS/LFLiveKit#208]
我试了必须同时设置下beautifyFace，才能生效，  还有如何让推流端的画面不是镜像而拉流的画面是镜像？

**Comment by chenliming777** [comment]
GPUImageVideoCamera @property(readwrite, nonatomic) BOOL horizontallyMirrorFrontFacingCamera, horizontallyMirrorRearFacingCamera;
