### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by RockyPanchal** [LaiFengiOS/LFLiveKit#209]
i try to run example with given sample url : "rtmp://live.hkstv.hk.lxdns.com:1935/live/stream153"
and i face below error every time
ERROR: PILI_RTMP_ReadPacket, failed to read PILI_RTMP packet header
plz help me to get out from this error

**Comment by yxf0103** [comment]
same problem
 rtmp://live.hkstv.hk.lxdns.com:1935/live/stream153 maybe not reachable
try build a local rtmp server,and replace the url
