### ISSUE TITLE
你好，运行例子总是出现ERROR: PILI_RTMP_ReadPacket, failed to read PILI_RTMP packet header，请问怎么解决，谢谢

### ISSUE THREAD

**Issue by tmac24** [LaiFengiOS/LFLiveKit#211]

**Comment by bairdweng** [comment]
同求

**Comment by lyc2345** [comment]
this issue haven't been fixed, why close?

**Comment by b9AobJ** [comment]
The problem was with your RTMP server rejecting the stream. Nothing wrong with this. Great work, by the way.

**Comment by biyu6** [comment]
原因是连接失败。您可以尝试将URL更改为您自己的服务器的URL; 或者试试这个：（rtmp：//116.196.87.91：1935 / live / VC000099）注意“VC000099”是自定义的，不要与其他人重复。推荐两个测试软件：OBS，VLC
