### ISSUE TITLE
Support resolution when camera is in landscape mode

### ISSUE THREAD

**Issue by timothytlewis** [LaiFengiOS/LFLiveKit#218]
We have followed the following tickets:

https://github.com/LaiFengiOS/LFLiveKit/issues/139

https://github.com/LaiFengiOS/LFLiveKit/issues/155

We are unable to get the LFLiveKit to go into widescreen mode. Using the outputImageOrientation we are able to send the RTMP to our server in widescreen mode, but the encoded image is not oriented properly. 

Has anyone been able to get this working?

**Comment by timothytlewis** [comment]
It does not work in the swift sample application. When rotated to landscape mode it has the same issue that I am experiencing. 

Thoughts? Thank you.

**Comment by romanfurman6** [comment]
@timothytlewis if i understand right, [its](https://stackoverflow.com/questions/28278072/force-ios-view-to-not-rotate-while-still-allowing-child-to-rotate) must help you.
But i left only portrait orientation.

**Comment by timothytlewis** [comment]
Thank you, @romanfurman6 I will test with that today.

**Comment by chenliming777** [comment]
set outputImageOrientation &  LFLiveVideoConfiguration videoSize
