### ISSUE TITLE
Is there a way to access the each video frame and is it possible to add overlay object to video frame?

### ISSUE THREAD

**Issue by lzzhangar** [LaiFengiOS/LFLiveKit#220]
I am new to this. This is a question on iOS

I wonder if there is a way to access to image of each video frame. There is a UIImage *currentImage property in LFLiveSession, however, the LFLiveSession delegate callback is only triggered when live state change.

If I can access each video frame, I would like to overlay objects to the video frame. Is this possible?

Thanks

**Comment by y4nnick** [comment]
You can set a watermark view with `  self.session?.warterMarkView = self.overlayView` where overlayView is a simple UIView

**Comment by lzzhangar** [comment]
thanks @y4nnick.

is there are way to access to each video frame? For instance, iOS provides this delegate AVCaptureVideoDataOutputSampleBufferDelegate in AVFoundation. LFLiveKit uses this as well in the GPUImageVideoCamera, however, what is the API to access so that I can get image from each video frame? What I want to do is the get image from each video frame, process the image to create a overlay (using waterMarkView). thanks

**Comment by y4nnick** [comment]
I don't know how you can get each frame out, but why aren't you just using the waterMarkView? 
The watermark overlays over the original video.

**Comment by lzzhangar** [comment]
I want to process each frame and update watermarkView in each frame. So I need to access each video frame.

I added a delegate to LFLiveSession
`- (void)liveSession:(nullable LFLiveSession *)session pixelBuffer:(nullable CVPixelBufferRef)pixelBuffer;
`
and invoked this callback at `- (void)captureOutput:(nullable LFVideoCapture *)capture pixelBuffer:(nullable CVPixelBufferRef)pixelBuffer 
`

Not sure if it is best / right way to achieve thought. I am looking for is if LFLiveKit has an API or delegate that allow me to do that.

**Comment by chenliming777** [comment]
LFLiveSession @property (nonatomic, strong,readonly, nullable) UIImage *currentImage;

**Comment by lzzhangar** [comment]
@chenliming777  thanks. I saw this property. Is there a delegate function or callback to notify the application that video frame has been updated where I can use currentImage property?

**Comment by lzzhangar** [comment]
@chenliming777 Just want to follow up on this. I tried to use LFLiveSession currentImage and in 
`- (void)captureOutput:(nullable LFVideoCapture *)capture pixelBuffer:(nullable CVPixelBufferRef)pixelBuffer`

however the currentImage is always nil, but the pixelBuffer isn't. Is this expected? I. could technically convert pixelBuffer to UIImage, but I don't want to do that for performance reason.

anybody else can advise? I basically want to have a callback to know each UIImage frame in the video.

thanks
