### ISSUE TITLE
Support resolution when camera is in landscape mode #218 REOPENED

### ISSUE THREAD

**Issue by timothytlewis** [LaiFengiOS/LFLiveKit#222]
This issue was NOT resolved. 

https://github.com/LaiFengiOS/LFLiveKit/issues/218

In each of the landscape posts (there are now 3) the suggestion is the same: 
outputImageOrientation & LFLiveVideoConfiguration 

outputImageOrientation does, in fact, send the video to the streaming service as landscape, BUT the video is encoded in portrait mode. 

LFLiveVideoConfiguration similarly does not work correctly. 

Even the test project does not work for this properly. 

If anyone could try getting this to work, perhaps update the test project, I would be grateful. 

Thank you,

TTL

**Comment by wangzhe890703** [comment]
Any update on this issue?

**Comment by timothytlewis** [comment]
Just checking to see if anyone has had a moment to check into this. It's been driving me crazy trying to get it to work! Any thoughts?

Thank you!

**Comment by ghost** [comment]
In file LFVideoCapture.m:
Change UIApplicationWillChangeStatusBarOrientationNotification -> UIApplicationDidChangeStatusBarOrientationNotification
And:
- (void)statusBarChanged:(NSNotification *)notification {
    NSLog(@"UIApplicationDidChangeStatusBarOrientationNotification. UserInfo: %@", notification.userInfo);
    UIInterfaceOrientation statusBar = [[UIApplication sharedApplication] statusBarOrientation];
    if(self.configuration.autorotate){
        self.configuration.outputImageOrientation = statusBar;
        [self.configuration refreshVideoSize];
        self.videoCamera.outputImageOrientation = statusBar;
        [self reloadFilter];
    }
}

In LFLiveVideoConfiguration.m, add function:
- (void)refreshVideoSize {
    CGSize size = self.videoSize;
    if(self.landscape) {
        CGFloat width = MAX(size.width, size.height);
        CGFloat height = MIN(size.width, size.height);
        self.videoSize = CGSizeMake(width, height);
    } else {
        CGFloat width = MIN(size.width, size.height);
        CGFloat height = MAX(size.width, size.height);
        self.videoSize = CGSizeMake(width, height);
    }
}

Last, set autorotate = true
=> It's worked for me
Hope this helps.

**Comment by timothytlewis** [comment]
So excited to try. I will let you know if there are any issues! Thank you!

**Comment by timothytlewis** [comment]
You've done it! 

Amazing. 

One additional note: 

To the LFLiveVideoConfiguration.h config:
add: 

/* The refreshVideoSize is set the Video Refresh Size */
@property (nonatomic, assign) BOOL refreshVideoSize;

@blackblack915 if I could gift you fake internet point, I would do so. You have completely brightened my day. 

Thank you.

**Comment by rinfosho** [comment]
HI, I know its been a while but when blackblack915 mentioned to set autorotate to true, where do you set it as true?
