### ISSUE TITLE
How to capture screen? 

### ISSUE THREAD

**Issue by pavan4** [LaiFengiOS/LFLiveKit#227]
I am trying to use the sdk to capture screen . I tried this currently but it doesn't work 

```
  var Lsession: LFLiveSession = {
    let audioConfiguration = LFLiveAudioConfiguration.defaultConfiguration(for: LFLiveAudioQuality.high)
    let videoConfiguration = LFLiveVideoConfiguration.defaultConfiguration(for: LFLiveVideoQuality.low3)
    let session = LFLiveSession(audioConfiguration: audioConfiguration, videoConfiguration: videoConfiguration)
    return session!
  }()
  let stream = LFLiveStreamInfo()
  stream.url = "rtmp://domain.com:1935/show/testS"
  Lsession.pushVideo(frame.capturedImage)
```

How can I initialize the session with screen capture? Any pointers?

**Comment by pavan4** [comment]
I had to set captureType and it worked after that.

let session = LFLiveSession(audioConfiguration: audioConfiguration, videoConfiguration: videoConfiguration, captureType: LFLiveCaptureTypeMask.inputMaskVideo)

**Comment by devajith** [comment]
Are you able to send audio from ARKit ?

**Comment by jap99** [comment]
Where did the frame come from?

**Comment by jap99** [comment]
I see in the code you're using the pushVideo instance method and passing in a frame. My question for you is how / from where is this frame being captured?

**Comment by harsh12312** [comment]
Hey there, is there any way to send audio data to live stream along with the video which is recorded from phone? My main goal is to play some song in background during video streaming from device camera.
