### ISSUE TITLE
Accept other video input

### ISSUE THREAD

**Issue by ltebean** [LaiFengiOS/LFLiveKit#24]
Great library! I wonder can you make it more flexible by allowing users to specify the video input, for example, making `LFVideoCapture` an protocol and then let `LFLiveSession` accept an `LFVideoCapture` implementation. The implementation can call `- (void)captureOutput:(nullable LFVideoCapture*)capture pixelBuffer:(nullable CVImageBufferRef)pixelBuffer;
` to specify the video input.

Thanks!

**Comment by chenliming777** [comment]
I know what you mean, but the only question is how to align the time stamp. External input data inside how to make a time stamp?

**Comment by ltebean** [comment]
What timestamp? Do you mean the `currentTimestamp` here?
```
- (void)captureOutput:(nullable LFVideoCapture*)capture pixelBuffer:(nullable CVImageBufferRef)pixelBuffer{
    [self.videoEncoder encodeVideoData:pixelBuffer timeStamp:self.currentTimestamp];
}
```
From the current implementation, it is generated every time the method gets called

**Comment by chenliming777** [comment]
yes，You transmit the data is encoded before or after the coding。If the incoming data is encoded, then there is a problem.

**Comment by ltebean** [comment]
I need to broadcast part of my screen, here is what I did, and it works.

```
self.session.videoCaptureSource.running = NO; // disable video capture
CVPixelBufferRef pixelBuffer = [self pixelBufferFromView:self.containerView]; // convert a UIView to CVPixelBufferRef
[self.session captureOutput:nil pixelBuffer: pixelBuffer]; // make it as video input
```

So I wonder If you can change the api to better support it

**Comment by ltebean** [comment]
Just as https://github.com/pili-engineering/PLStreamingKit and https://github.com/pili-engineering/PLCameraStreamingKit. The StreamingKit accepts `PixelBuffer` as input, while the CameraStreamingKit offers camera capture func and it uses StreamingKit to broadcast. It will be more flexible to allow users to specify video and audio input. Thanks!

**Comment by chenliming777** [comment]
ok Will be perfect as soon as possible

**Comment by zzgo** [comment]
I think so . I need to share image of my screen.Like this:

` CVPixelBufferRef pixelBuffer =[self pixelBufferFromView:self.containerView]; `
   ` CIImage *ciImage = [CIImage imageWithCVPixelBuffer:pixelBuffer];`

**Comment by chenliming777** [comment]
External input interface has been added, you can look at the next master branch

**Comment by jeejjang** [comment]
Would you show me the external input way by codes?

**Comment by longld103** [comment]
I has live streaming success from external input (Gear 360) but on preview screen only showing black. I think that it is get input from internal camera to showing preview.
