### ISSUE TITLE
当我使用后置摄像头的时候 显示的方向不对 还有当我旋转屏幕的时候 显示的方向也不对 求作者大大支援

### ISSUE THREAD

**Issue by XuBaoLoveEatFish** [LaiFengiOS/LFLiveKit#25]

**Comment by XuBaoLoveEatFish** [comment]
只有前置摄像头而且 不改变屏幕方向 显示方向才对

**Comment by chenliming777** [comment]
我这边测后置没发现问题呀，你可以给我发邮件，QQ沟通一下具体问题

**Comment by chenliming777** [comment]
这个问题怎么样了，横屏需要注意两三点。第一：videoConfiguration.landscape参数设置为YES，第二：- (UIInterfaceOrientationMask)supportedInterfaceOrientations这个方法需要支持横屏。第三：APP需要支持横屏

**Comment by YXMao** [comment]
我这边也是，只要打开系统的重力感应，初始化为竖屏，当屏幕旋转的时候，显示的方向就不对，我看了一下设置，你以上提到的三点我都做了，不过设置landscape=YES的时候，会抛异常： @throw [NSException exceptionWithName:@"当前设置方向出错" reason:@"LFLiveVideoConfiguration landscape error" userInfo:nil];

**Comment by chenliming777** [comment]
这里错误的意思就是当前你landscape设置为YES了   就必须是横屏，你说的初始化为竖屏与这个参数冲突导致的

**Comment by chenliming777** [comment]
这个修改了  测一下最新代码吧
