### ISSUE TITLE
Is it possible to use this LFLiveKit with a Broadcast Upload Extension?

### ISSUE THREAD

**Issue by homanp** [LaiFengiOS/LFLiveKit#257]
Hi, 

In iOS 11 one can get a live feed of the screen using ReplyKit 2 and a Broadcast Upload Extension. Is it possible to utilize LFLiveKit for the streaming part? 

How would one go about doing this?

Thanks!

**Comment by homanp** [comment]
Ok so it seems one can use the `pushVideo`/`pushAudio` options here. Great

**Comment by cprovatas** [comment]
@homanp did you ever solve? having issues getting to work with extension
