### ISSUE TITLE
pod搜不到啊

### ISSUE THREAD

**Issue by wct1991** [LaiFengiOS/LFLiveKit#27]
arondeMacBook-Pro:MiaowShow aron$ pod search LFLive
[!] Unable to find a pod with name matching `LFLiveKit'

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `LFLiveKit`

通过pod搜不到这个库

**Comment by chenliming777** [comment]
是不是你那边pod需要更新一下库  pod repo update    然后pod search LFLiveKit

**Comment by wct1991** [comment]
谢谢，果然大神还是大神。
