### ISSUE TITLE
one frame while streaming

### ISSUE THREAD

**Issue by grzeg91** [LaiFengiOS/LFLiveKit#277]
When I start streaming on iPhone 7 I see on VLC only first frame, but sound is streaming good. 
As server i use wowza. 
Use Sample from Github. On phone video is good, but on vlc player is only first frame.

**Comment by eeekw** [comment]
@grzeg91  why did you close? Did you find the answer?

**Comment by darnfish** [comment]
Having this issue too. Any resolution - is this a problem with VLC?
