### ISSUE TITLE
在打开All Exception的情况下,startLive后会断点在AudioConverterNewSpecific这个函数

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#28]
如下图
![qq20160726-0 2x](https://cloud.githubusercontent.com/assets/6426556/17137006/2a8bb084-536b-11e6-923b-b628cf6a32c8.png)

**Comment by hellerchen** [comment]
另外非常感谢作者你开源的这个库!~

**Comment by chenliming777** [comment]
抱歉，目前还真是不清楚原因，知道了会解答的

**Comment by zzgo** [comment]
之前我用videoCore时也有这样的问题，好像是因为有一些c或c++代码运行就会引发全局断点。不知道对不对，仅供参考
