### ISSUE TITLE
无法在iOS Extension中使用

### ISSUE THREAD

**Issue by huchao** [LaiFengiOS/LFLiveKit#292]
在iOS11中采用ReplayKit2录屏，然后用LFLiveKit转码推流，最终推流失败。
如下为具体步骤：
1. 将LFLiveKit添加至ReplayKit2的Extension中
2. 编译失败，原因为[UIApplication sharedApplication].idleTimerDisabled = YES/NO;
3. 将所有类似代码注释掉
4. 编译通过后，最终在手机上运行时报错：
XReplayKitUploadExtension[491:18291] [aurioc] 1422: AUIOClient_StartIO failed (561145187)

请问LFLiveKit能做到支持iOS Extension不？

**Comment by zhuozhuo** [comment]
兄弟你遇到应用外录制视频时，视频方向问题没？

**Comment by huchao** [comment]
ReplayKit2返回的裸视频帧永远保持一个方向，但有个Flag可以读取到方向值。
