### ISSUE TITLE
EXC_BAD_ACCESS (code=EXC_ARM_DA_ALIGN, address=0x103b)

### ISSUE THREAD

**Issue by yaoqiang8808** [LaiFengiOS/LFLiveKit#30]
在iPhone5连接Xcode中真机测试中出现内存错误.
断开数据线运行并没有影响.
我将异常信息提供在下面.非常感谢你们的开源分享,希望做的更好.

xcode  Version 7.3.1 (7D1014)
iPhone5  iOS 8.3
pod 'LFLiveKit', '~> 1.6'

代码位置:
GPUImageView.m Line 168
[[[GPUImageContext sharedImageProcessingContext] context] renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer*)self.layer];

日志信息:
device iPhone5,1
model iPhone5
num 5

线程信息:
* thread #1: tid = 0x55eaf, 0x0145a3bc libglInterpose.dylib`EAGLContext_renderbufferStorageFromDrawable(EAGLContext*, objc_selector*, unsigned int, id<EAGLDrawable>) + 204, queue = 'com.sunsetlakesoftware.GPUImage.openGLESContextQueue', stop reason = EXC_BAD_ACCESS (code=EXC_ARM_DA_ALIGN, address=0x103b)
    frame #0: 0x0145a3bc libglInterpose.dylib`EAGLContext_renderbufferStorageFromDrawable(EAGLContext*, objc_selector*, unsigned int, id<EAGLDrawable>) + 204
  * frame #1: 0x00364402 -[GPUImageView createDisplayFramebuffer](self=0x073eed60, _cmd="createDisplayFramebuffer") + 342 at GPUImageView.m:168

    frame #2: 0x00363efc __26-[GPUImageView commonInit]_block_invoke(.block_descriptor=0x0128a4f8) + 1608 at GPUImageView.m:129

    frame #3: 0x014fdea4 libdispatch.dylib`_dispatch_barrier_sync_f_invoke + 96

    frame #4: 0x0033f70c runSynchronouslyOnVideoProcessingQueue(block=0x0128a4f8) + 102 at GPUImageOutput.m:44

    frame #5: 0x003638a0 -[GPUImageView commonInit](self=0x073eed60, _cmd="commonInit") + 810 at GPUImageView.m:97

    frame #6: 0x00363492 -[GPUImageView initWithFrame:](self=0x073eed60, _cmd="initWithFrame:", frame=(origin = (x = 0, y = 0), size = (width = 320, height = 568))) + 168 at GPUImageView.m:63

    frame #7: 0x00306ce6 -[LFVideoCapture initWithVideoConfiguration:](self=0x073d39c0, _cmd="initWithVideoConfiguration:", configuration=0x073cf280) + 874 at LFVideoCapture.m:37

    frame #8: 0x002fa960 -[LFLiveSession videoCaptureSource](self=0x073cf6b0, _cmd="videoCaptureSource") + 132 at LFLiveSession.m:219

    frame #9: 0x002fa40a -[LFLiveSession setRunning:](self=0x073cf6b0, _cmd="setRunning:", running=YES) + 204 at LFLiveSession.m:173

**Comment by hellerchen** [comment]
你这个问题是8.3系统上面的bug,具体可以去GPUImage官网查到相关的issue讨论
临时解决办法可以参考下图,Capture opengl设置为disable,另外也可以选择更新iOS版本
![qq20160728-0 2x](https://cloud.githubusercontent.com/assets/6426556/17199229/ed1e04ec-54ad-11e6-9130-fae0078dabd2.png)
