### ISSUE TITLE
Can LFLiveKit record screen instead of camera?

### ISSUE THREAD

**Issue by wuzhiming** [LaiFengiOS/LFLiveKit#300]
Can LFLiveKit record screen instead of camera?
I want to live a game ，but I can't find the docs about this. 
@toss156 can you give me a help?

**Comment by toss156** [comment]
建议使用 Replaykit2 配合 金山或者七牛，支持麦克风和游戏声音混合。用 LFLiveKit 的话，需要改动比较多，混音这块得自己做。

**Comment by wuzhiming** [comment]
谢谢大神帮忙解答@toss156， 因为需要支持armv7和ios8+，所以 replaykit2 被pass了哎。。。
能否请问大神，还有没有什么方案可以选呢？想实现的功能是公司的游戏接入Facebook 的 live video（rtmp） ，混音可以先忽略。

**Comment by toss156** [comment]
@wuzhiming 
如果是自己公司的游戏的话，只在游戏内进行直播的话，那么基本上的SDK都可以实现，游戏引擎那边把当前画面转成 CVPixelBufferRef 传过来就可以了。
其他通用的录屏方案你可以了解下，但是对你们来说可能不是特别合适。
[iOS 游戏直播方案简介](https://toss156.github.io/2018/11/30/ReplayKit2%20%E7%9B%B4%E6%92%AD/)

**Comment by toss156** [comment]
也可以用 UIView 截屏的方式来做，但是效率不是很高。

**Comment by wuzhiming** [comment]
@toss156 非常感谢您的解答~~ 

再次感谢。。。

**Comment by zj381652512** [comment]
之前做直播+录制用的LFLiveKit,GPUImageMovieWriter

现在新需求要在直播中加一个切换局部录屏的功能,局部录屏这块我采用的截屏方式,切换摄像头与录屏时,同时还要保证录制数据无缝拼接, 感觉GPUImageMovieWriter是指望不上了(在LFLiveKit用GPUImageMovieWriter存视频底部肯定有编码, 推流前也要编码, 感觉有点过度编码, 增大了消耗)

我想在音视频编码以后, 一边推流, 一边保存mp4到本地, 请问有没有库能将 H264编码及AAC编码后的数据封装为mp4?

**Comment by zj381652512** [comment]
> 也可以用 UIView 截屏的方式来做，但是效率不是很高。

之前做直播+录制用的LFLiveKit,GPUImageMovieWriter

现在新需求要在直播中加一个切换局部录屏的功能,局部录屏这块我采用的截屏方式,切换摄像头与录屏时,同时还要保证录制数据无缝拼接, 感觉GPUImageMovieWriter是指望不上了(在LFLiveKit用GPUImageMovieWriter存视频底层有编码, 推流前也要编码, 感觉有点过度编码, 增大消耗)

我想在音视频编码以后, 一边推流, 一边保存mp4到本地, 请问有没有库能将 H264编码及AAC编码后的数据封装为mp4?

**Comment by toss156** [comment]
FFmpeg 可以实现h264 acc 合成MP4。 但是这个主要需求的性能瓶颈应该是截屏这边吧，之前测试过基本上达不到20帧。至于编码的话，现在基本上都是硬解编码，编两次问题也不大。
另外：之前做过一个类似的需求是在服务端拉取ts切片进行合成MP4，不在客户端处理。

**Comment by zj381652512** [comment]
> FFmpeg 可以实现h264 acc 合成MP4。 但是这个主要需求的性能瓶颈应该是截屏这边吧，之前测试过基本上达不到20帧。至于编码的话，现在基本上都是硬解编码，编两次问题也不大。
> 另外：之前做过一个类似的需求是在服务端拉取ts切片进行合成MP4，不在客户端处理。

感谢回复!  之所以想在编码后保存mp4, 主要是摄像头与录屏切换时,用GPUImageMovieWriter做录制不好衔接,摄像头时用的添加target方式, 录屏时需要接收CVPixelBuffer, 其次才是两次编码消耗问题

**Comment by zj381652512** [comment]
本文记录的程序将一个H.264编码的视频码流文件和一个MP3编码的音频码流文件，合成为一个MP4封装格式的文件。
https://blog.csdn.net/leixiaohua1020/article/details/39802913/

**Comment by GirirajMulay** [comment]
could you provide me the feedback in English?
Could please provide me some example (code snippet to understand workflow)
