### ISSUE TITLE
请问LFLiveKit可以支持纯音频的推流吗或者说可以通过某些技巧来屏蔽视频流部分？

### ISSUE THREAD

**Issue by YXMao** [LaiFengiOS/LFLiveKit#32]

**Comment by chenliming777** [comment]
![870b2348-4167-4253-a226-d47f03f4c531](https://cloud.githubusercontent.com/assets/8952943/17211976/f5f922bc-54fe-11e6-8bdc-6d7b91f755f5.png)
![03842906-fdab-471c-8bea-12adb568b14d](https://cloud.githubusercontent.com/assets/8952943/17212011/23ce40a0-54ff-11e6-8c9b-611291322332.png)
![5c5eff95-7a5c-4e6c-94ac-1517e8b7957f](https://cloud.githubusercontent.com/assets/8952943/17212037/3e7cad74-54ff-11e6-9105-d60eead54b8b.png)
目前想到的是这三个地方做优化，第一个只开音频，第二个不要增加码率，第三个丢帧策略需要优化（可以干脆丢掉最老的帧）

**Comment by YXMao** [comment]
非常感谢，如果是要同时推送一个音视频和和这个音视频中的音频到两个不同的rtmp地址，会不会有问题，我之前试了下，音视频可以推上去，但纯音频推流会有问题？

**Comment by chenliming777** [comment]
这个很麻烦，我还没有做过，你这需要传输到2个地址。

**Comment by chenliming777** [comment]
@YXMao  纯音频接口已经添加了，可以看下master分支下最新提交

**Comment by chenliming777** [comment]
不可以这样  只能单独推送音频  或者单独推送视频
