### ISSUE TITLE
直播过程中播放端闪屏问题

### ISSUE THREAD

**Issue by liubinhai122586** [LaiFengiOS/LFLiveKit#324]
直播过程偶现视频流闪屏问题，不同平台和设备播放同时闪屏

**Comment by zj381652512** [comment]
直播ok---push--->录屏直播ok---pop--->直播闪屏

![屏幕快照 2019-12-26 下午6 57 10](https://user-images.githubusercontent.com/17876394/71473375-aff75b00-2811-11ea-8ef4-7a271b0e2ea8.png)

我在_session.running = YES 后面加了一段代码如下:

    AVCaptureSession *session   = [[AVCaptureSession alloc] init];
    AVCaptureDevice *device     = [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo].lastObject;
    AVCaptureDeviceInput *input = [AVCaptureDeviceInput deviceInputWithDevice:device error:nil];
    if ([session canAddInput:input]) {
        [session addInput:input];
    }

闪屏竟然没了,不理解.....

**Comment by liubinhai122586** [comment]
定位发现，开启美颜的情况下，推流端显示用户点赞等比较耗性能的动画效果或输入框键盘弹出/关闭时z会出现闪烁，使用zj381652512的方法完美解决。建议推流端不要显示太复杂的动画，或使用zj381652512的方法解决。

**Comment by yzc773825166** [comment]
> 定位发现，开启美颜的情况下，推流端显示用户点赞等比较耗性能的动画效果或输入框键盘弹出/关闭时z会出现闪烁，使用zj381652512的方法完美解决。建议推流端不要显示太复杂的动画，或使用zj381652512的方法解决。

您好，我也遇到相同问题，使用zj381652512的方法好像不起作用
