### ISSUE TITLE
Audio keeps a crackling noise while using headset bluetooth

### ISSUE THREAD

**Issue by noho501** [LaiFengiOS/LFLiveKit#334]
Hi,

Thanks for great library. It works well, but I have one issue can't resolve it. When I connected my Airpods (all headphone via bluetooth) to stream to Youtube the sound crackle here is this video https://youtu.be/YdIaNxicyNI

Anyone have an idea how to fix it?

**Comment by tomihr** [comment]
We also had this problem when streaming to Youtube, we fix it by changing the way timestamp is created.
I can post our solution if that is ok?

**Comment by noho501** [comment]
@tomihr Yes, please share us solution to fix this issue

**Comment by libracohoang** [comment]
I also had this issue, could you please share your solution @tomihr ?

**Comment by noho501** [comment]
Anyone have an idea how to fix it?

**Comment by unathi-dev** [comment]
@tomihr , can you please share your solution ? I am facing the same issue.
