### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [LaiFengiOS/LFLiveKit#35]
```CocoaPods``` and ```Carthage``` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the *Manual installation* guide in your ```README.md```. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by chenliming777** [comment]
Good thank you for comments today.

**Comment by chenliming777** [comment]
Good thank you for comments today.

**Comment by chenliming777** [comment]
Good thank you for comments today.
