### ISSUE TITLE
Video in livestream gets blinking Only in large Devices

### ISSUE THREAD

**Issue by chandrikadevis** [LaiFengiOS/LFLiveKit#357]
Short description
Video get blinks in live stream only on iPhone large device.

Environment

Operating system and version: iOS Version 10.15.7
Xcode12.2
Swift 4.2
iPhone 11 Version 14.3
Steps to reproduce

Open app in iPhone 11 device
Publish streaming
Watch the video in other android or iPhone device
Video get blinks. This issue happened on all large iPhone devices.
Expected behavior
There should be smooth play without any blinking.

Actual behavior
Video get blinks in when record in large devices.

Reference Video: http://13.56.209.242/WebRTCAppEE/streams/Stream_DHPAvSzeZGRI.mp4

**Comment by bbkelleroglu** [comment]
Hey,

In the LFLiveSession object there are two parameters which are beautyLevel, beautyFace. if you set them 0.0 and false, you won't see any blinking problem.

Here is the sample code: 

`var session: LFLiveSession = {
        let audioConfiguration = LFLiveAudioConfiguration.defaultConfiguration(for: LFLiveAudioQuality.high)
        let videoConfiguration = LFLiveVideoConfiguration.defaultConfiguration(for: LFLiveVideoQuality.high2)
        let session = LFLiveSession(audioConfiguration: audioConfiguration, videoConfiguration: videoConfiguration)
        session?.beautyFace = false
        session?.beautyLevel = 0.0
        return session!
    }()`

**Comment by chandrikadevis** [comment]
Hi @bbkelleroglu ,
Thanks for your support, it's working for me.

**Comment by haihoang88** [comment]
Hi @bbkelleroglu ,
Can this issue be solved without turning OFF the beautyFace? We really want to use the beautyFace feature.
