### ISSUE TITLE
用 pod 'LFLiveKit'，出错，求指导

### ISSUE THREAD

**Issue by danwey** [LaiFengiOS/LFLiveKit#36]
在 NALUnit.h 里提示 class 不可用。
NALUnit.h  改成 NALUnit.hpp 后，又提示 #include <openssl/bn.h> 没找到。

**Comment by chenliming777** [comment]
你这边是object－c？另外你是编译不过去，还是ios7直播使用不了

**Comment by danwey** [comment]
swift 工程， 编译不过去 使用 pod 'LFLiveKit' 的

**Comment by chenliming777** [comment]
这个代码里面有这个LFLiveKitSwiftDemo 需要添加桥接的文件（LFLiveKitSwiftDemo-Bridging-Header）你先参考下，有问题在交流

**Comment by danwey** [comment]
桥接的文件 添加了。。现在是 编译不过去，好吧，我先看看LFLiveKitSwiftDemo工程先，不行时再请教。谢谢了。

**Comment by zhangyu528** [comment]
在 LFLiveKitSwiftDemo中,修改 如下
source 'https://github.com/CocoaPods/Specs.git'
**platform :ios,'8.0'
use_frameworks!**
target 'LFLiveKitSwiftDemo' do
pod 'LFLiveKit', path: '../'
end
**bridging header.h 中编译报错，Could not build module 'LFLiveKit'**

**Comment by chenliming777** [comment]
use_frameworks!这个参数一般是OC工程调用swift工程用的吧，swift工程调用oc需要桥接文件，还真没有swift工程用这个参数。

**Comment by zhangyu528** [comment]
嗯是的, 但想用这个use_frameworks!这个参数设定后pod生成的是swift 的framework, 非.a

**Comment by chenliming777** [comment]
这个目前不知道怎么解决，等有结果了会在这里通知。抱歉。。

**Comment by danwey** [comment]
我现在是用您的demo里的LFLiveKit，当子工程加入到我的工程里，可用。

**Comment by chenliming777** [comment]
这样改完好了嘛
![93ba92f3-1abf-4187-918b-1c57eb2da7c3](https://cloud.githubusercontent.com/assets/8952943/17355256/ca4df494-5981-11e6-8b5f-d1980338e001.png)

**Comment by zhangyu528** [comment]
如果用use_framework,就不需要bridging了，可以直接在swift中， import LFLiveKit

**Comment by chenliming777** [comment]
确实，厉害，谢谢了。那这个问题原来／＊＊／＊.h是什么原因不行呢？学习一下 哈哈

**Comment by zhangyu528** [comment]
貌似public 里面C的头文件影响了到module了

**Comment by chenliming777** [comment]
哦哦  了解了 谢谢
