### ISSUE TITLE
How can I switch to back camera?

### ISSUE THREAD

**Issue by AntonKuznetsov** [LaiFengiOS/LFLiveKit#4]
Hello
Could you please tell me how can I switch to back camera? 
The lib uses frontal camera by default.
Thanks

**Comment by AntonKuznetsov** [comment]
Nevermind, I've found the answer my self.
Thanks for the awesome library!

**Comment by chenliming777** [comment]
you can try captureDevicePosition

**Comment by ollydixon** [comment]
@AntonKuznetsov Ah man, how selfish. How did you solve this?

**Comment by ollyde** [comment]
Example of switching camera's.

```self.session.captureDevicePosition = (AVCaptureDevice.Position.front == session.captureDevicePosition) ? .back : .front```
