### ISSUE TITLE
Failed to start Video Camera on iOS7

### ISSUE THREAD

**Issue by chamroeunbm** [LaiFengiOS/LFLiveKit#41]
Hi,
I use iOS7.1 on iPad mini2.
My camera video failed:
-----
Assert - (kernResult == kIOReturnSuccess) - f: /SourceCache/AppleVXE380/AppleVXE380-403/Library/AppleVXE380UserLandLibrary.cpp l: 494
AppleVXE380VA ERROR: IOServiceOpen failed
Assert - (false) - f: /SourceCache/AppleVXE380/AppleVXE380-403/Library/AppleVXE380FIGwrapper.cpp l: 3106
VXE FIG: H264VideoEncoderVA_DriverCreate failed.
-----

Any suggestion?
Thanks;

**Comment by toss156** [comment]
I have just test it use iOS 7.1.1 on iPhone5, and it works fine.  
Need more infomation.

**Comment by chamroeunbm** [comment]
Sorry. I didn't update to the 2.0. It works fine after updating
