### ISSUE TITLE
观看端看到的画面模糊

### ISSUE THREAD

**Issue by Michael-Owen** [LaiFengiOS/LFLiveKit#43]
推上去的流是不是有问题？在观看端看到的画面时常很模糊，不管怎么设置，明显不如直播端预览的画面清晰，尤其直播端在动的时候，观看端看到的画面都是胡的。不知道是什么原因呢？
另外滤镜感觉反光好严重啊，感觉还没有最早的版本好呢。

**Comment by chenliming777** [comment]
你自己配置videoBitRate这个看看，想要清晰这里设置800*100～1200*100测一下吧。

**Comment by Michael-Owen** [comment]
一样的，我之前设过，直接用demo里面下面那个配置，设置videoConfiguration.videoBitRate = 800*1024; 直播端在动的时候，观看端可以明显看到画面模糊。你把主播端的手机前后左右晃动很容易看到。看了下源代码，不知道是哪里出的问题。

**Comment by hellerchen** [comment]
@Michael-Owen 这个是因为做了动态bitrate

**Comment by Michael-Owen** [comment]
@hellerchen 是的。我也看到那段代码了，但是就算我将动态码率的代码注释掉了，貌似也是比较模糊的，感觉还是不是那么清晰。你们试试呢？我不知道还有其他地方影响吗。

**Comment by toss156** [comment]
如果觉得运动状态比较模糊的话，就只能把码率调高一点，移动直播始终是在码率和画质上面做取舍。
另外直播端看到肯定是比观看端清楚的，直播端看到都是没有经过编码的。

**Comment by Michael-Owen** [comment]
@toss156 你们调高了效果理想吗？我都调到800k+了，不算低了吧，画面还是很模糊啊，哪怕把动态码率的代码注释掉了。效果也很一般吧。和我目前在用的or试过的一些sdk对比，同样的码率等效果差距还是蛮大的。关键是我不知道是哪些部分代码影响到了（同码率下）。

**Comment by toss156** [comment]
@Michael-Owen 同码率，同分辨率么？ 有可能是videotoolbox那边的设置的不一样

**Comment by hellerchen** [comment]
@Michael-Owen 其实码率800k+一点都不算高,正如@toss156说的,码率和画质上需要做一个折中取舍.
不过你说的同码率下存在差异,这个倒有追查的必要,期望你能定位到问题,把解决办法在这里分享给大家.
 PS:你说的or是啥?一个推流SDK?

**Comment by Michael-Owen** [comment]
@toss156 恩，有可能，我抽空仔细看看那部分的代码，研究下。
@hellerchen 恩，我们现在用的是别人的推流sdk，也试用了一些其他开源和厂商的。800k+不算高吗？之前用的别人的sdk，我设置的是800，后来另外一个公司自己做的推流，他说动态码率也就是300-800，很少达到800的。

**Comment by hellerchen** [comment]
@Michael-Owen 800k的码率在我看来顶多算是标清偏高清级别,带宽够的情况下1000k~1500k才算高清,可以参考下图(引用自斗鱼)
![201403291720051198](https://cloud.githubusercontent.com/assets/6426556/17474165/33ef6da2-5d87-11e6-9aae-fe3a1368dcb8.jpg)

**Comment by toss156** [comment]
@Michael-Owen 我还有个猜测是 可能是SessionPreset 引起的，之前用VideoCore的话一般都是用最高的录制，然后缩放成需要的size，可以试试 所有的用AVCaptureSessionPreset1280x720的试试，和原来的AVCaptureSessionPresetiFrame960x540 做下对比

**Comment by Michael-Owen** [comment]
@chenliming777 @hellerchen @toss156 最近一直忙着发版本，都没来得及看，今天看了下源代码，果然是编码造成的问题。LFHardwareVideoEncoder.m文件中，105行，    CMTime presentationTimeStamp = CMTimeMake(frameCount, 1000);
timescale设置的太大了，把1000改为1就可以了。

**Comment by chenliming777** [comment]
ok 感谢

**Comment by ilaoxia** [comment]
还是很模糊，特别是直播端在动的时候，观看端画面模糊, 我的设置：
![image](https://user-images.githubusercontent.com/11848254/29905785-4048e608-8e43-11e7-96d9-176c99753dae.png)
