### ISSUE TITLE
I can't pods installed 

### ISSUE THREAD

**Issue by frost-htx** [LaiFengiOS/LFLiveKit#45]
pod install
Unable to find a specification for `LFLiveKit

pod search LFLiveKit
[!] Unable to find a pod with name, author, summary, or descriptionmatching `LFLiveKit`

I use xcode 7.2

**Comment by chenliming777** [comment]
you can try pod repo update

**Comment by frost-htx** [comment]
it's no luck for me..

**Comment by frost-htx** [comment]
pod repo update
rm ~/Library/Caches/CocoaPods/search_index.json 
☑️

**Comment by chenliming777** [comment]
ok
