### ISSUE TITLE
关于LFLiveVideoConfiguration类中supportSessionPreset的方法使用疑问

### ISSUE THREAD

**Issue by YXMao** [LaiFengiOS/LFLiveKit#48]
![2016-08-10 10 59 31](https://cloud.githubusercontent.com/assets/12440054/17540556/a9143226-5ee9-11e6-91e8-8b4a15e85963.png)

请问楼主以上的代码逻辑是不是有点问题哦，第一次 **if (![session canSetSessionPreset:avSessionPreset])** 即不支持当前设置的分辨率之后，从上到下依次下降分辨率，但是当赋值sessionPreset = LFCaptureSessionPreset540x960之后，又再一次判断 **if (![session canSetSessionPreset:avSessionPreset])** ，之后设置sessionPreset = LFCaptureSessionPreset360x640;这样做判断是不是有问题哦？

**Comment by toss156** [comment]
没有问题吧， 判断不支持 720p 以后，再 判断能否支持540p ，如果还不能的话，选择360p。

**Comment by chenliming777** [comment]
可能还真有问题  应该if (![session canSetSessionPreset:avSessionPreset]) 改为if (![session canSetSessionPreset:self.avSessionPreset]) 重新调用一次

**Comment by chenliming777** [comment]
这个已经修改了，可以看下最新提交

**Comment by YXMao** [comment]
好的，我想问下现在你们的库Pod进来后用到了GPUImage，跟我之前工程pod的GPUImage的文件发生了重复和冲突，请问应该咋个解决喃

**Comment by ApesTalk** [comment]
if (![session canSetSessionPreset:self.avSessionPreset]) {
        if (sessionPreset == LFCaptureSessionPreset720x1280) {
            sessionPreset = LFCaptureSessionPreset540x960;
            if (![session canSetSessionPreset:self.avSessionPreset]) {
                sessionPreset = LFCaptureSessionPreset360x640;
            }
        } else if (sessionPreset == LFCaptureSessionPreset540x960) {
            sessionPreset = LFCaptureSessionPreset360x640;
        }
    }

现在最新的这样写，不是依然多判断了一次吗？

**Comment by Mamong** [comment]
写得罗里吧嗦地，最后还写错了。。。

**Comment by hongkong792** [comment]
您好，我已收到您的邮件，感谢您对我的支持！香港回复
