### ISSUE TITLE
Please advice RTMP Playback

### ISSUE THREAD

**Issue by AntonKuznetsov** [LaiFengiOS/LFLiveKit#5]
Hello
Thank you for your awesome library, it's so much better than VideoCore!

But it's hard to find a reliable library to actually view the stream. Could you please advice me the best one for iOS in your opinion?

**Comment by chenliming777** [comment]
https://github.com/Bilibili/ijkplayer

**Comment by chenliming777** [comment]
The library supports great variety of formats，contain rtmp
