### ISSUE TITLE
在4G环境下推流异常

### ISSUE THREAD

**Issue by BossKing** [LaiFengiOS/LFLiveKit#51]
在4G环境下采集推流控制台提示:
handleRouteChange reason is The category of the session object changed.
handleRouteChange reason is The output route was overridden by the app.
数据应该没有推出去!

**Comment by chenliming777** [comment]
你打印这个信息关于AVAudioSession切换导致的，但是否传出去没有你确认嘛？或者有什么毕现的步骤没有

**Comment by chenliming777** [comment]
需要更多的信息，没有复现

**Comment by BossKing** [comment]
请问我在WiFi环境下是OK的,切换到移动4G(iOS9.3.4, iPhone6S Plus)连接超时,控制台输出:
device iPhone8,2
model iPhone8
num 8
handleRouteChange reason is The category of the session object changed.
MicrophoneSource: startRunning
handleRouteChange reason is The output route was overridden by the app.
handleRouteChange reason is The category of the session object changed.
ERROR: PILI_RTMP_Connect0, failed to connect socket. 60 (Operation timed out)
应该可以排除4G环境不好的情况,因为总是连接不成功!请问在4G环境下需要额外配置些什么信息吗?

**Comment by chenliming777** [comment]
不用额外配置的呀，这样你下载下其它的库可以试试

**Comment by chenliming777** [comment]
你这边问题怎么样了   还是4G不能直播嘛，我也用9.3.4的系统  但未发现

**Comment by BossKing10086** [comment]
不好意思,这么晚给你回复邮件,之前我利用花生壳域名(内网IP与外网IP之间的映射)搭建了一个nginx的外网服务器,怎么都不可以,即使使用别的SDK也是一样,在4G环境下无法推流,这两天试着租了一台阿里服务器,系统是CentOS,排除了防火墙的影响,验证在4G下是可以推流的,只是延迟有点大,可能与网络环境有关,实在不好意思,应该是系统环境的影响!

**Comment by BossKing** [comment]
不好意思,这么晚给你回复邮件,之前我利用花生壳域名(内网IP与外网IP之间的映射)搭建了一个nginx的外网服务器,怎么都不可以,即使使用别的SDK也是一样,在4G环境下无法推流,这两天试着租了一台阿里服务器,系统是CentOS,排除了防火墙的影响,验证在4G下是可以推流的,只是延迟有点大,可能与网络环境有关,实在不好意思,应该是系统环境的影响!

**Comment by chenliming777** [comment]
ok
