### ISSUE TITLE
Adding custom filters...

### ISSUE THREAD

**Issue by telip007** [LaiFengiOS/LFLiveKit#53]
How could I add custom filters ?

**Comment by telip007** [comment]
More specific, let the user draw on the video while live streaming, like in the facebook live streams...

**Comment by telip007** [comment]
Like add an layer over the capture and stream it with it... For example the drawings in Facebook live or Snapchat when recording a video...

**Comment by chenliming777** [comment]
@telip007  about add custom filter:  support your input CVPixelBuffer

**Comment by chenliming777** [comment]
@telip007  the second question，waterMark？ No matter what, you can own input video，So can be achieved

**Comment by telip007** [comment]
From which class I can access input videoData ? Sorry I'm new to Streams on iOS :)

**Comment by telip007** [comment]
For example where do have to use this [Text Overlay recorded Video](http://stackoverflow.com/questions/30609241/render-dynamic-text-onto-cvpixelbufferref-while-recording-video) in which function

**Comment by chenliming777** [comment]
you can see LFLiveCaptureType

- (void)pushVideo:(CVPixelBufferRef)pixelBuffer;
- (void)pushAudio:(AudioBufferList)audioBufferList;

**Comment by telip007** [comment]
@chenliming777 OK thank you got it :)

**Comment by y4nnick** [comment]
I wanna overlay a image (or multiple ones) over the video. Is this doable with the pushVideo or should i use the watermark feature? 
Could someone please provide some sample code? I am using the LFLiveKitSwiftDemo App.
Thanks!
