### ISSUE TITLE
I make react-native module from your kit

### ISSUE THREAD

**Issue by KwonOhBin** [LaiFengiOS/LFLiveKit#55]
hello.

I develop app from based react-native

so i make react-native module to customize based your project

thanks.

https://www.npmjs.com/package/react-native-video-stream

**Comment by chenliming777** [comment]
I am sorry to reply you so late that you have updated a version of 2.2.4.3 pod. You will have a good test to keep the communication with you.

**Comment by pvinis** [comment]
im also wrapping this library for an ios app in react native. but i dont know how to make a library. i also need some more this to be added, so i will make a fork of this project and submit pull requests as i go.
