### ISSUE TITLE
pod install  LFLiveKitDemo 报 ld: library not found for -lLFLiveKit

### ISSUE THREAD

**Issue by ryanypm** [LaiFengiOS/LFLiveKit#57]
![image](https://cloud.githubusercontent.com/assets/7519919/17761074/bf99ebd2-6536-11e6-8d0c-803cfe22bf87.png)

还有一个问题，我单独新建一个项目pod 'LFLiveKit' 好像需要platform 8.0才能行
而且版本跟现在down下来的版本不一样

**Comment by ryanypm** [comment]
更新 cocoapod 就可以了 ~~~

**Comment by chenliming777** [comment]
ok
