### ISSUE TITLE
1.6版本推流看不到画面

### ISSUE THREAD

**Issue by wangjuniOS6** [LaiFengiOS/LFLiveKit#6]
推流画面是白屏

**Comment by chenliming777** [comment]
谢谢反馈    一会我跟踪一下

**Comment by chenliming777** [comment]
你指的是本地还是远端呢

**Comment by chenliming777** [comment]
这边这个问题也是测试的1.6   https://github.com/chenliming777/LMLiveStreaming/issues?q=is%3Aissue+is%3Aclosed   貌似最后测试没问题   希望给出更多的操作步骤  不胜感谢

**Comment by toss156** [comment]
设备型号和版本也提供下呗，可能和美颜有关，之前碰到过黑屏的。

**Comment by chenliming777** [comment]
嗯  都提供一下吧  我这边也复现一下

**Comment by zzgo** [comment]
我这里也是一样，最近几次1.6经常出现推流到服务器黑屏。只有声音，没有画面

**Comment by chenliming777** [comment]
这个还真没有遇到，先更新版本测一下吧，后续有问题在交流

**Comment by yjg2014** [comment]
我也遇到只有声音没图像的问题，抓到的流分析是0.0fps。以下是我用ijkplayer抓取的log信息：
av_version_info: ff3.0--ijk0.4.5.1--dev0.4.5--rc10
ijkmp_set_inject_opaque(0x167732a0)
ijkmp_set_inject_opaque()=void
OK setup GL
ijkmp_ios_set_view(glView=0x1678d550)
ijkmp_ios_set_view(glView=0x1678d550)=void

ijkmp_set_data_source(url="xxxxxxxx")
ijkmp_set_data_source(url=“xxxxxx")=0
ijkmp_prepare_async()

ijkmp_set_inject_opaque(0x1678b340)
ijkmp_set_inject_opaque()=void
ijkmp_stop()

ijkmp_stop()=0

ijkmp_prepare_async()=0

ijkmp_ios_set_view(glView=0x1aa6a040)
ijkmp_ios_set_view(glView=0x1aa6a040)=void

setupDisplay not ready
unable to tryLock GL active: 0
ijkmp_shutdown_l()=void
ijkmp_dec_ref(): ref=0
ijkmp_shutdown_l()
ijkmp_shutdown_l()=void
aout_close_audio()
