### ISSUE TITLE
iPhone6 Plus下推流有时会出现音视频不同步的问题

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#61]
iPhone6 Plus下推流有时会出现音视频不同步的问题,音频会比画面延时大概1~3s
有可能不是推流端问题,但是我这边很难定位到点,请问能提供一点思路方向不?

**Comment by chenliming777** [comment]
可以   你这样， 你在传输数据之前判断是否缓冲区内部有视频关键帧与音频帧（看下是否可能一个设备先打开一个后打开）

**Comment by chenliming777** [comment]
这个已经修复了  你查看最新master版本测试一下吧

**Comment by hellerchen** [comment]
@chenliming777 哟西,非常感谢还在继续跟进这个问题!~
