### ISSUE TITLE
多次尝试都没有吧项目运行起来。。。

### ISSUE THREAD

**Issue by cooliean** [LaiFengiOS/LFLiveKit#64]
真的太失败了我。。。
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

有又一样错误的人嘛，谢谢告知。
我是pod 1.0.1

下载源码后，我就只在demo目录下面运行了pod install ，编译项目就报错了。

**Comment by chenliming777** [comment]
pod repo update
