### ISSUE TITLE
希望把人脸检测加上

### ISSUE THREAD

**Issue by jianshek** [LaiFengiOS/LFLiveKit#65]
滤镜可以根据不同的需求自己写，还是希望把人脸检测加上，这样使用更方便些

**Comment by chenliming777** [comment]
这个还需要您自己处理，目前我这边不支持，但是支持传入rgb或者yuv数据进行上传（LFLiveKit进行编码与上传）。

**Comment by yjg2014** [comment]
在SDK基础如何做人脸关键点检测？
