### ISSUE TITLE
在ipv6下测试推流 客户端观看是黑屏。不支持IPv6吗？

### ISSUE THREAD

**Issue by limeng10086** [LaiFengiOS/LFLiveKit#66]
感谢回答。

**Comment by chenliming777** [comment]
这个我这边是支持的，我在本地建了一个ipv6的网络，测试没问题

**Comment by toss156** [comment]
也可能是播放器不支持的。 推流这边librtmp已经支持ipv6了

**Comment by limeng10086** [comment]
@toss156 我用的ijkplayer 不支持ipv6播放吗？

**Comment by toss156** [comment]
@limeng10086  ijkplayer是支持的，我自己测试的时候也是部分cdn支持，部分cdn不支持。另外不要用ip的形式播放视频，用ip是肯定播不出来的。

**Comment by limeng10086** [comment]
@toss156 好的，那我就再找找原因吧，谢谢指教。
