### ISSUE TITLE
关于一个weak strong dance的问题

### ISSUE THREAD

**Issue by BossKing** [LaiFengiOS/LFLiveKit#67]
release版本2.1中LFStreamingBuffer.m中方法tick:
__weak typeof(self) _self = self;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(self.updateInterval * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        __weak typeof(_self) self = _self;
        [self tick];
    });
确定里面不使用__strong吗?

**Comment by chenliming777** [comment]
感谢指出   已经修改
