### ISSUE TITLE
直播本地收录

### ISSUE THREAD

**Issue by zhangzhichaoGit** [LaiFengiOS/LFLiveKit#68]
如何将录制直播视频保存在本地一份，请作者给个思路 谢谢。江湖救急啊

**Comment by toss156** [comment]
LFHardwareVideoEncoder 可以看到录制视频的方法，但是没有声音的。
建议加在LFLiveSession里面的
`
- (void)audioEncoder:(nullable id<LFAudioEncoding>)encoder audioFrame:(nullable LFAudioFrame *)frame {
    if (self.uploading) [self.socket sendFrame:frame];  //<上传
}

- (void)videoEncoder:(nullable id<LFVideoEncoding>)encoder videoFrame:(nullable LFVideoFrame *)frame {
    if (self.uploading) [self.socket sendFrame:frame];  //<上传
}

`
这两个方法里面。获取编码完的video和audio帧写入文件。

**Comment by chenliming777** [comment]
这个目前已经支持了存储AAC     AudioEncoder里面

**Comment by zhangzhichaoGit** [comment]
把编码完成的 音频， 视频 2个流 怎么才能写到一个文件里，不会用到FFMPEG库吧

**Comment by chenliming777** [comment]
这个我本地写了一个flv   比较麻烦  你可以查看之前commit记录

**Comment by zhangzhichaoGit** [comment]
- (void)localFeaturesVideo
{
    NSString * pathToMovie = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents/movie.m4v"];
    unlink([pathToMovie UTF8String]);
    self.outputfilter = [[GPUImageSaturationFilter alloc] init];
    NSURL *movieURL = [NSURL fileURLWithPath:pathToMovie];
    [self.videoCamera addTarget:self.outputfilter];
    [self.outputfilter addTarget:self.gpuImageView];

    _movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(640, 360)];
    _movieWriter.encodingLiveVideo = YES;
    _movieWriter.shouldPassthroughAudio = YES;
     self.videoCamera.audioEncodingTarget = _movieWriter;
   
    [self.outputfilter addTarget:_movieWriter];
   
    [_movieWriter startRecording];
}
本地收录我已经完成了 在LFVideoCapture里加上这个 就可以了 谢谢你们的直播开源库写的真心好。

**Comment by chenliming777** [comment]
好的  玩些时候会添加的
