### ISSUE TITLE
弱网内存爆炸

### ISSUE THREAD

**Issue by bobonovski** [LaiFengiOS/LFLiveKit#7]
你好，我们在测试的过程发现，网络不好的时候内存会一直往上长，多到100多MB。网络好的时候没有这个问题，不知道这是什么 BUG？！
谢谢解答

**Comment by toss156** [comment]
请问是怎么测试的网络不好的？

**Comment by chenliming777** [comment]
这个有其他人已经反馈了  我还没解决掉，跟踪到的问题是因为弱网出来的帧调用底层rtmp发送函数都成功了，但真实没有发送成功，所以我猜测底层有链表机制将上层传入的帧都存储起来了，然而真正发送成功的很少，造成了堆积导致的。所以目前需要找到哪里是真正发送成功的地方或者其它策略可以将发送几次发送不出去的帧丢掉

**Comment by chenliming777** [comment]
这个问题在最新版本1.6.7貌似解决了，关注的测一下吧
