### ISSUE TITLE
在推流成功后，在推流界面，创建一个使用ijk的拉流播放，没有声音。

### ISSUE THREAD

**Issue by lidscd** [LaiFengiOS/LFLiveKit#73]
https://pan.baidu.com/s/1pKYSZMz ijk包

**Comment by chenliming777** [comment]
你测一下最新2.2.2.4  另外这个问题不一定是推流端问题   也可能是底层播放器   总而言之是AVAudioSession出问题了

**Comment by lidscd** [comment]
我尝试一下别的播放器试试。感谢啊。

**Comment by chenliming777** [comment]
ijk底层播放器category貌似是AVAudioSessionCategoryPlayback   你需要改为AVAudioSessionCategoryPlayAndRecord（边录音边播放）
