### ISSUE TITLE
丢帧策略的疑惑

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#75]
<img width="574" alt="qq20160901-0 2x" src="https://cloud.githubusercontent.com/assets/6426556/18156950/d6be4aee-704c-11e6-8177-1d586570f373.png">
<img width="419" alt="qq20160901-1 2x" src="https://cloud.githubusercontent.com/assets/6426556/18156952/d9417ec6-704c-11e6-8196-78f7abb2b24c.png">
你好,按上面的逻辑,如果是needDropFrame = NO的情况下,不就会执行了两次[self.list lfPopFirstObject],造成丢了一帧画面?

**Comment by chenliming777** [comment]
是的  这里确实有问题  我改一下  感谢

**Comment by chenliming777** [comment]
已经修复了 谢谢
