### ISSUE TITLE
屏幕旋转。。。。捂头

### ISSUE THREAD

**Issue by yuyedaidao** [LaiFengiOS/LFLiveKit#76]
在允许屏幕旋转的情况下，如果竖直进入，显示正常，然后转动屏幕触发屏幕旋转，这时候显示的不正常，然后最关键的是，如果在竖直起来屏幕旋转之后影像是上下颠倒的

**Comment by toss156** [comment]
这个我也碰到了，目前的办法是 不去监听UIApplicationWillChangeStatusBarOrientationNotification的通知，直播界面固定横竖屏。

**Comment by yuyedaidao** [comment]
@toss156 产品要求能在直播过程中自由切换屏幕

**Comment by chenliming777** [comment]
你说的捂头是什么意思  没看懂

**Comment by yuyedaidao** [comment]
@chenliming777  😄请忽略表达情绪的词语。。。。 问题在描述里简单说了一下，就是屏幕旋转有点乱，没法满足直播过程中自由切换屏幕的需求

**Comment by chenliming777** [comment]
这个最新版本修改了一下  你这边测试一下吧(设置下面两个)
@property (nonatomic, assign) BOOL autorotate;
@property (nonatomic, assign) UIInterfaceOrientation outputImageOrientation;

**Comment by yuyedaidao** [comment]
可不可以往pod上推一下，pod上还是旧的，多谢

**Comment by chenliming777** [comment]
这个下周更新吧  因为需要测试的  再等等吧

**Comment by yuyedaidao** [comment]
videoConfiguration.autorotate = YES;
     videoConfiguration.outputImageOrientation = UIInterfaceOrientationLandscapeLeft;
我这样设置后发现显示的图像在手机上还是旋转了90度的，虽然通过VLC看方向对了

**Comment by manajay** [comment]
我想监测状态栏,改变输出流的方向,发现没用
        _session.streamInfo.videoConfiguration.outputImageOrientation =  UIInterfaceOrientationLandscapeRight;

**Comment by chenliming777** [comment]
这个内部检测了  你设置autorotate就应该好了（如果是真的旋转设备的情况下，旋转view不适用）

**Comment by manajay** [comment]
@chenliming777  如果我锁定竖屏方向的话, 设置 autorotate , 那么输出的视频流,也会自动切换吗?
第二种情况, 我不锁定竖屏呢?

**Comment by manajay** [comment]
@chenliming777  我测试了, 发现设置了 autorotate 为 YES 也不行
/// 自动旋转(这里只支持 left 变 right  portrait 变 portraitUpsideDown)
@property (nonatomic, assign) BOOL autorotate;

**Comment by manajay** [comment]
- (LFLiveVideoSessionPreset)supportSessionPreset:(LFLiveVideoSessionPreset)sessionPreset {
能把 这里面 支持的AVCaptureSessionPreset 多一些,能够改变或者 直接使用系统的常量;
我在做 横屏的时候, 拍摄时 显示在自己屏幕上的尺寸,和 输出流的屏幕尺寸根本对不上

**Comment by chenliming777** [comment]
输出流的屏幕尺寸是videoSize，sessionPreset只是分辨率，它们为什么要对上呢？

**Comment by WeiChaoZheng** [comment]
这个问题是 需要在初始化 Session 的时候进行转向录制的方向的设置,
设置videoConfiguration
+ (instancetype)defaultConfigurationForQuality:(LFLiveVideoQuality)videoQuality outputImageOrientation:(UIInterfaceOrientation)outputImageOrientation
和设置 videoConfiguration. autorotate = YES; 如果刚刚开始支持竖屏,然后才需要转屏的话,重新设置 _session.streamInfo.videoConfiguration.outputImageOrientation; 这个是没用的,需要重新初始化session,这个有点麻烦,希望作者能改进,提点建议.
