### ISSUE TITLE
关于丢帧的策略问题

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#77]
needDropFrame=NO的前提下,在网络情况非常不理想的情况下(例如3G),本地缓存会不断累积,例如下图
![weaknetwork](https://cloud.githubusercontent.com/assets/6426556/18162568/8180221a-7069-11e6-8ca4-cbaa41d1b975.png)

这里会有几个问题:
1.缓存累积得越多,拉流端延迟就会越来越大
2.如果网络恢复正常,累积的缓存越多,拉流端就会快进得越久
3.开启丢帧,拉流端会经常花屏
4.内存会可能增大一个很大的数字

请问,有什么好的处理建议?

**Comment by chenliming777** [comment]
needDropFrame = NO  肯定是有一大堆问题的  设置为YES花屏也正常 因为你网速太差了  P帧丢完了还不可以

**Comment by chenliming777** [comment]
这个很难做到平衡，  我代码已经去掉了needDropFrame ， 因为设置为NO延迟太大了。你可以尝试最低码率设置低一些，动态切换码率来达到不花屏

**Comment by hellerchen** [comment]
@chenliming777 好的,感谢回复

**Comment by VictorQi** [comment]
丢帧策略上可以修改一下，只丢p帧而保留i帧，花屏多原因在于i帧的数据丢失了，画面没有解码出来

**Comment by VictorQi** [comment]
并且修改vt的编码参数可以降低花屏

**Comment by chenliming777** [comment]
目前策略就是只丢P帧  保留I帧与音频帧      你调整buffer长度试试
