### ISSUE TITLE
adaptiveBitrate=YES的情况下,videoBitRate可能一下子就会降到最低值

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#78]
有两种情况:
1.在网络非常好的情况下,也会一下子降到videoMinBitRate
2.不会触发LFLiveBuffferDecline(videoBitRate = videoMaxBitRate)

**Comment by chenliming777** [comment]
adaptiveBitrate 为YES嘛

**Comment by hellerchen** [comment]
@chenliming777 测试了几台手机,iPhone6,iPhone6s plus,bitrate=800, 推流开始不久就会降到videoMinBitRate,而且码率不会再提高

**Comment by chenliming777** [comment]
好的 收到  我这边调试一下  前提是这个adaptiveBitrate一定要为YES  另外你网速怎么样   如果非常差肯定是这样的效果

**Comment by hellerchen** [comment]
@chenliming777 adaptiveBitrate是YES,网络环境肯定是正常的,上下行10M光钎

**Comment by chenliming777** [comment]
确实有bug 已经修复了
