### ISSUE TITLE
支持软编码吗 ？

### ISSUE THREAD

**Issue by dingfude2008** [LaiFengiOS/LFLiveKit#79]
如题， 硬编码的情况下，接收端如果使用软解码，会有绿边

**Comment by chenliming777** [comment]
这个绿边不是解码的问题  如果你设置videoSize为368 640  或者直接设置720 1280 应该没问题

**Comment by chenliming777** [comment]
另外软编码可以参考一下https://github.com/chenliming777/LMSoftCodeDemo

**Comment by dingfude2008** [comment]
按照你的步骤， 我设置videoSize为368 640 或者直接设置720 1280 ,  在IJKPlayer中播放还是有绿边的，大概有10个像素，但是在 VLC中是正常的， 不知道是什么问题导致的，我下载了LiveVideoCoreSDK，测试发现，它推流的在IJKPlayer中播放，也是有绿边的，大概有2个像素，同样在VLC中是正常的。不知道是哪里出了问题，求指教

**Comment by chenliming777** [comment]
你采集分辨率多少

**Comment by dingfude2008** [comment]
LFLiveAudioConfiguration *audioConfiguration = [LFLiveAudioConfiguration new];
         audioConfiguration.numberOfChannels = 2;
         audioConfiguration.audioBitrate = LFLiveAudioBitRate_128Kbps;
         audioConfiguration.audioSampleRate = LFLiveAudioSampleRate_44100Hz;
         
         LFLiveVideoConfiguration *videoConfiguration = [LFLiveVideoConfiguration new];
         videoConfiguration.videoSize = CGSizeMake(368, 640 );//CGSizeMake(720, 1280);
         videoConfiguration.videoBitRate = 800*1024;
         videoConfiguration.videoMaxBitRate = 1000*1024;
         videoConfiguration.videoMinBitRate = 500*1024;
         videoConfiguration.videoFrameRate = 15;
         videoConfiguration.videoMaxKeyframeInterval = 30;
         videoConfiguration.orientation = UIInterfaceOrientationPortrait;
         videoConfiguration.sessionPreset = LFCaptureSessionPreset720x1280;
         
         _session = [[LFLiveSession alloc] initWithAudioConfiguration:audioConfiguration videoConfiguration:videoConfiguration liveType:LFLiveRTMP];

**Comment by dingfude2008** [comment]
这样推流到服务器，然后使用IJKPlayer  软解码播放，右边带绿边。。 APP咱不支持硬解码

**Comment by chenliming777** [comment]
好的 我测一下

**Comment by dingfude2008** [comment]
测试有结果了吗  ？

**Comment by chenliming777** [comment]
非常抱歉  这么晚给你回复  今天测了一下，如果videoSize设置为368 640我这边没有问题（IJK软解码）

**Comment by dingfude2008** [comment]
我在测试一下，可能是我这边的其他问题影响到了，稍后我再回复
