### ISSUE TITLE
大哥，我用swift的例子推流会卡住了

### ISSUE THREAD

**Issue by ghyh22** [LaiFengiOS/LFLiveKit#83]
LFFrame *firstFrame = [self.sortList lfPopFirstObject];
有时会崩溃在这

**Comment by chenliming777** [comment]
这个应该是配置的问题（－allload）   你现在测一下

**Comment by ghyh22** [comment]
好了，thanks

**Comment by longqingling** [comment]
Build Settings --> Linking->  Other Linker Flags 中加上 -ObjC 或者-all_load
