### ISSUE TITLE
Carthage build issue

### ISSUE THREAD

**Issue by justinswart** [LaiFengiOS/LFLiveKit#84]
Carthage says:

> *** Skipped building LFLiveKit due to the error:
> Dependency "LFLiveKit" has no shared framework schemes for any of the platforms: iOS

**Comment by zzgo** [comment]
I have same issue when i use carthage

**Comment by chenliming777** [comment]
这个暂时不支持了  因为GPUImage源码倒入会产生一些问题

**Comment by pvinis** [comment]
what issues would it cause?

**Comment by chenliming777** [comment]
it's ok  version 2.5
