### ISSUE TITLE
请问如何开启日志打印？

### ISSUE THREAD

**Issue by primeant** [LaiFengiOS/LFLiveKit#85]
比如推流过程中打印视频的码率之类的。

**Comment by primeant** [comment]
/** live debug info callback */
- (void)liveSession:(nullable LFLiveSession *)session debugInfo:(nullable LFLiveDebug *)debugInfo {
    NSLog(@"debugInfo uploadSpeed: %@", formatedSpeed(debugInfo.currentBandwidth, debugInfo.elapsedMilli));
}
推流过程中没看到回调。

**Comment by primeant** [comment]
_session.showDebugInfo = YES;可以了。
除了打印LFLiveDebug里的属性信息，还可不可以打印更多信息

**Comment by chenliming777** [comment]
暂时不可以   你提出来如何合理可以加入到debug里面  
你还想要什么信息呢

**Comment by primeant** [comment]
嗯嗯，先看看
