### ISSUE TITLE
How to stream cropped video 4:3 aspect ratio

### ISSUE THREAD

**Issue by AdamLuisSean** [LaiFengiOS/LFLiveKit#86]
Can I stream cropped video to server like photo example?:
![screen shot 2016-09-07 at 5 25 16 pm](https://cloud.githubusercontent.com/assets/10870984/18385112/4ab9a6fa-7697-11e6-89a4-94ea30f1b7f0.png)

**Comment by chenliming777** [comment]
you can set videoSize 4:3
