### ISSUE TITLE
推流是有时会收到这个错误该如何处理

### ISSUE THREAD

**Issue by wangjuniOS6** [LaiFengiOS/LFLiveKit#89]
ERROR: PILI_RTMP_ReadPacket, failed to read PILI_RTMP packet header
收到此错误信息后,还会回调- (void)liveSession:(nullable LFLiveSession *)session liveStateDidChange:(LFLiveState)state
} state状态为LFLiveStop

**Comment by chenliming777** [comment]
内部逻辑是重连会走一次stop start的过程
