### ISSUE TITLE
分享遇到问题

### ISSUE THREAD

**Issue by NengQuan** [LaiFengiOS/LFLiveKit#91]
当我在直播过程中分享，跳转回原来直播页面 ，就卡住了，画面不再动
![img_1500](https://cloud.githubusercontent.com/assets/15306400/18606605/3c7f33c4-7ce7-11e6-9894-0284d3769679.PNG)

**Comment by zzgo** [comment]
因你从切换回来，推流中断了，重新start

**Comment by NengQuan** [comment]
我改过来了 上面显示是已连接 ，流也在推 ，就是画面不动。卡在那

**Comment by zzgo** [comment]
session.running改成YES了吗？

**Comment by NengQuan** [comment]
![img_1534](https://cloud.githubusercontent.com/assets/15306400/18628029/c642ed4e-7e90-11e6-93b7-05a1b1c26438.PNG)
我设置了running 为yes了 但有时候 分享回来进行直播会出现这个白屏 ，几率挺高的

**Comment by chenliming777** [comment]
我这边还没有遇到这个问题  您那边看能不能找到一个复现的步骤

**Comment by NengQuan** [comment]
可以 ，就是进入直播前分享到朋友圈，在分享页面停留20秒，回来就是白屏了 。停留时间短不会白屏

**Comment by dourgulf** [comment]
@NengQuan iOS版本是多少?是不是比较集中在iOS8上出现? 之前使用VideoCore就遇到过(在iOS8上高频率发生). 主要的原因是OpenGL的绘制出现一些问题.

**Comment by dourgulf** [comment]
楼主有空一起加到QQ群里交流一下经验吧

**Comment by LibraSkywalker** [comment]
Xcode8.1 ios10.1 Apple Mach-O Liner Error, undefined LFLiveSession, LFLiveStream

用的是Swift, Manually imported,

**Comment by LibraSkywalker** [comment]
Problem solved
