### ISSUE TITLE
请问defaultSortBufferMaxCount的改动作用是什么?

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#97]
你好,我看到最新的代码defaultSortBufferMaxCount从10改为1,请问这样改动的意义是什么?
按我的理解,这样改动好像效率会降低?

**Comment by chenliming777** [comment]
改动后可以降低延迟  本地目前我这里测试延迟从100多毫秒降低到了10几毫秒，原来有一个10的buffer就是延迟，但我没有测是否所有的服务器都支持无序传输（相近的几个数据无序）

**Comment by hellerchen** [comment]
@chenliming777 能告诉我一下你测试过的推流服务器不?
另外按你的解释,不是把defaultSortBufferMaxCount设为2~9也是可以降低延迟(同时实现有序传输)?

**Comment by chenliming777** [comment]
是的   服务器就是目前的preView里面那个地址

**Comment by hellerchen** [comment]
@chenliming777 试了一下,改为1之后,声音会变成一卡一卡的

**Comment by chenliming777** [comment]
那我先改成5吧
