### ISSUE TITLE
LFStreamRtmpSocket在某些情况不会重连

### ISSUE THREAD

**Issue by hellerchen** [LaiFengiOS/LFLiveKit#98]
你好,看了一下代码,在RTMP264_Connect中,PILI_RTMP_SetupURL,PILI_RTMP_Connect,PILI_RTMP_ConnectStream失败都会跳到错误,而没有做重连动作.这个情况是不是在LFLiveSocketError_ConnectSocket自己做重连动作?

**Comment by chenliming777** [comment]
是的 目前设计时这样的

**Comment by hellerchen** [comment]
@chenliming777 找到一个无限重连的bug,在LFStreamRTMPSocket->reconnect->_stop中,每次都会把retryTimes4netWorkBreaken这个值重置,导致(socket.retryTimes4netWorkBreaken++ < socket.reconnectCount && !socket.isReconnecting)永远为真,无限重连

**Comment by chenliming777** [comment]
好的 我看一下  非常感谢

**Comment by hellerchen** [comment]
不用谢,要谢也是我感谢你们开源的这个项目.现在我只是反哺
