### ISSUE TITLE
RTMP Auth problem

### ISSUE THREAD

**Issue by SDPuid** [LaiFengiOS/LFLiveKit#99]
能不能在pili_rtmp中加入验证

**Comment by chenliming777** [comment]
这个暂时没有研究过  我抽时间研究一下吧  如果你会的话  直接pull Request

**Comment by toss156** [comment]
带验证代码的librtmp 是GPL协议的，pili_rtmp 是基于LGPL版本的librtmp，所以没有验证部分，只能自己加

**Comment by YSBigBug** [comment]
librtmp带有验证机制，不过在我们的LF中直接将pili替换了，并不能达到验证目的

**Comment by toss156** [comment]
需要设置用户名密码，具体的设置方法可以参考obs中的。

**Comment by YSBigBug** [comment]
就是在验证这里卡住了

**Comment by YSBigBug** [comment]
rtmp://user:pwd@

**Comment by toss156** [comment]
把user 和 pwd 解析出来
` if (rtmpUser)
    {
        rtmp->Link.pubUser.av_val = rtmpUser;
        rtmp->Link.pubUser.av_len = (int)strlen(rtmpUser);
    }

    if (rtmpPass)
    {
        rtmp->Link.pubPasswd.av_val = rtmpPass;
        rtmp->Link.pubPasswd.av_len = (int)strlen(rtmpPass);
    }`

**Comment by YSBigBug** [comment]
else if (AVMATCH(&method, &av__error))
    {
#ifdef CRYPTO
      AVal methodInvoked = {0};
      int i;

      if (r->Link.protocol & RTMP_FEATURE_WRITE)
        {
          for (i=0; i<r->m_numCalls; i++)
            {
              if (r->m_methodCalls[i].num == txn)
                {
                  methodInvoked = r->m_methodCalls[i].name;
                  AV_erase(r->m_methodCalls, &r->m_numCalls, i, FALSE);
                  break;
                }
            }
          if (!methodInvoked.av_val)
            {
              RTMP_Log(RTMP_LOGDEBUG, "%s, received result id %f without matching request",
                    __FUNCTION__, txn);
              goto leave;
            }

          RTMP_Log(RTMP_LOGDEBUG, "%s, received error for method call <%s>", __FUNCTION__,
          methodInvoked.av_val);

          if (AVMATCH(&methodInvoked, &av_connect))
            {
              AMFObject obj2;
              AVal code, level, description;
              AMFProp_GetObject(AMF_GetProp(&obj, NULL, 3), &obj2);
              AMFProp_GetString(AMF_GetProp(&obj2, &av_code, -1), &code);
              AMFProp_GetString(AMF_GetProp(&obj2, &av_level, -1), &level);
              AMFProp_GetString(AMF_GetProp(&obj2, &av_description, -1), &description);
              RTMP_Log(RTMP_LOGDEBUG, "%s, error description: %s", __FUNCTION__, description.av_val);
              /* if PublisherAuth returns 1, then reconnect */
              if (PublisherAuth(r, &description) == 1)
              {
                CloseInternal(r, 1);
                if (!RTMP_Connect(r, NULL) || !RTMP_ConnectStream(r, 0))
                  goto leave;
              }
            }
        }
      else
        {
          RTMP_Log(RTMP_LOGERROR, "rtmp server sent error");
        }
      free(methodInvoked.av_val);
#else
      RTMP_Log(RTMP_LOGERROR, "rtmp server sent error");
#endif
服务器始终没有返回  user error错误

**Comment by YSBigBug** [comment]
OK了  参照OBS的，之前的问题在于没有配置
AVal av_flashVer = AVC("FMLE/3.0 (compatible; Lavf57.38.102)");

**Comment by duckscorpion13** [comment]
請問有詳細解法嗎？

**Comment by sdupidBoby** [comment]
这个库太久没更新了，不建议使用了哦
